// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pb_predict_pb_predict_Pipeline_LAYER0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_scaled_reload,
        input_scaled_1_reload,
        input_scaled_2_reload,
        input_scaled_3_reload,
        input_scaled_4_reload,
        input_scaled_5_reload,
        h_a_address0,
        h_a_ce0,
        h_a_we0,
        h_a_d0,
        h_a_1_address0,
        h_a_1_ce0,
        h_a_1_we0,
        h_a_1_d0,
        h_a_2_address0,
        h_a_2_ce0,
        h_a_2_we0,
        h_a_2_d0,
        h_a_3_address0,
        h_a_3_ce0,
        h_a_3_we0,
        h_a_3_d0,
        h_a_4_address0,
        h_a_4_ce0,
        h_a_4_we0,
        h_a_4_d0,
        h_a_5_address0,
        h_a_5_ce0,
        h_a_5_we0,
        h_a_5_d0,
        h_a_6_address0,
        h_a_6_ce0,
        h_a_6_we0,
        h_a_6_d0,
        h_a_7_address0,
        h_a_7_ce0,
        h_a_7_we0,
        h_a_7_d0,
        h_a_8_address0,
        h_a_8_ce0,
        h_a_8_we0,
        h_a_8_d0,
        h_a_9_address0,
        h_a_9_ce0,
        h_a_9_we0,
        h_a_9_d0,
        h_a_10_address0,
        h_a_10_ce0,
        h_a_10_we0,
        h_a_10_d0,
        h_a_11_address0,
        h_a_11_ce0,
        h_a_11_we0,
        h_a_11_d0,
        h_a_12_address0,
        h_a_12_ce0,
        h_a_12_we0,
        h_a_12_d0,
        h_a_13_address0,
        h_a_13_ce0,
        h_a_13_we0,
        h_a_13_d0,
        h_a_14_address0,
        h_a_14_ce0,
        h_a_14_we0,
        h_a_14_d0,
        h_a_15_address0,
        h_a_15_ce0,
        h_a_15_we0,
        h_a_15_d0,
        grp_fu_2052_p_din0,
        grp_fu_2052_p_din1,
        grp_fu_2052_p_opcode,
        grp_fu_2052_p_dout0,
        grp_fu_2052_p_ce,
        grp_fu_4258_p_din0,
        grp_fu_4258_p_din1,
        grp_fu_4258_p_opcode,
        grp_fu_4258_p_dout0,
        grp_fu_4258_p_ce,
        grp_fu_4262_p_din0,
        grp_fu_4262_p_din1,
        grp_fu_4262_p_opcode,
        grp_fu_4262_p_dout0,
        grp_fu_4262_p_ce,
        grp_fu_4266_p_din0,
        grp_fu_4266_p_din1,
        grp_fu_4266_p_opcode,
        grp_fu_4266_p_dout0,
        grp_fu_4266_p_ce,
        grp_fu_2057_p_din0,
        grp_fu_2057_p_din1,
        grp_fu_2057_p_dout0,
        grp_fu_2057_p_ce,
        grp_fu_4270_p_din0,
        grp_fu_4270_p_din1,
        grp_fu_4270_p_dout0,
        grp_fu_4270_p_ce,
        grp_fu_4274_p_din0,
        grp_fu_4274_p_din1,
        grp_fu_4274_p_dout0,
        grp_fu_4274_p_ce,
        grp_fu_4278_p_din0,
        grp_fu_4278_p_din1,
        grp_fu_4278_p_dout0,
        grp_fu_4278_p_ce,
        grp_fu_4282_p_din0,
        grp_fu_4282_p_dout0,
        grp_fu_4282_p_ce,
        grp_fu_4285_p_din0,
        grp_fu_4285_p_dout0,
        grp_fu_4285_p_ce,
        grp_fu_4288_p_din0,
        grp_fu_4288_p_dout0,
        grp_fu_4288_p_ce,
        grp_fu_4291_p_din0,
        grp_fu_4291_p_dout0,
        grp_fu_4291_p_ce,
        grp_fu_2067_p_din0,
        grp_fu_2067_p_din1,
        grp_fu_2067_p_opcode,
        grp_fu_2067_p_dout0,
        grp_fu_2067_p_ce,
        grp_fu_2072_p_din0,
        grp_fu_2072_p_din1,
        grp_fu_2072_p_opcode,
        grp_fu_2072_p_dout0,
        grp_fu_2072_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] input_scaled_reload;
input  [31:0] input_scaled_1_reload;
input  [31:0] input_scaled_2_reload;
input  [31:0] input_scaled_3_reload;
input  [31:0] input_scaled_4_reload;
input  [31:0] input_scaled_5_reload;
output  [4:0] h_a_address0;
output   h_a_ce0;
output   h_a_we0;
output  [31:0] h_a_d0;
output  [4:0] h_a_1_address0;
output   h_a_1_ce0;
output   h_a_1_we0;
output  [31:0] h_a_1_d0;
output  [4:0] h_a_2_address0;
output   h_a_2_ce0;
output   h_a_2_we0;
output  [31:0] h_a_2_d0;
output  [4:0] h_a_3_address0;
output   h_a_3_ce0;
output   h_a_3_we0;
output  [31:0] h_a_3_d0;
output  [4:0] h_a_4_address0;
output   h_a_4_ce0;
output   h_a_4_we0;
output  [31:0] h_a_4_d0;
output  [4:0] h_a_5_address0;
output   h_a_5_ce0;
output   h_a_5_we0;
output  [31:0] h_a_5_d0;
output  [4:0] h_a_6_address0;
output   h_a_6_ce0;
output   h_a_6_we0;
output  [31:0] h_a_6_d0;
output  [4:0] h_a_7_address0;
output   h_a_7_ce0;
output   h_a_7_we0;
output  [31:0] h_a_7_d0;
output  [4:0] h_a_8_address0;
output   h_a_8_ce0;
output   h_a_8_we0;
output  [31:0] h_a_8_d0;
output  [4:0] h_a_9_address0;
output   h_a_9_ce0;
output   h_a_9_we0;
output  [31:0] h_a_9_d0;
output  [4:0] h_a_10_address0;
output   h_a_10_ce0;
output   h_a_10_we0;
output  [31:0] h_a_10_d0;
output  [4:0] h_a_11_address0;
output   h_a_11_ce0;
output   h_a_11_we0;
output  [31:0] h_a_11_d0;
output  [4:0] h_a_12_address0;
output   h_a_12_ce0;
output   h_a_12_we0;
output  [31:0] h_a_12_d0;
output  [4:0] h_a_13_address0;
output   h_a_13_ce0;
output   h_a_13_we0;
output  [31:0] h_a_13_d0;
output  [4:0] h_a_14_address0;
output   h_a_14_ce0;
output   h_a_14_we0;
output  [31:0] h_a_14_d0;
output  [4:0] h_a_15_address0;
output   h_a_15_ce0;
output   h_a_15_we0;
output  [31:0] h_a_15_d0;
output  [31:0] grp_fu_2052_p_din0;
output  [31:0] grp_fu_2052_p_din1;
output  [0:0] grp_fu_2052_p_opcode;
input  [31:0] grp_fu_2052_p_dout0;
output   grp_fu_2052_p_ce;
output  [31:0] grp_fu_4258_p_din0;
output  [31:0] grp_fu_4258_p_din1;
output  [1:0] grp_fu_4258_p_opcode;
input  [31:0] grp_fu_4258_p_dout0;
output   grp_fu_4258_p_ce;
output  [31:0] grp_fu_4262_p_din0;
output  [31:0] grp_fu_4262_p_din1;
output  [1:0] grp_fu_4262_p_opcode;
input  [31:0] grp_fu_4262_p_dout0;
output   grp_fu_4262_p_ce;
output  [31:0] grp_fu_4266_p_din0;
output  [31:0] grp_fu_4266_p_din1;
output  [1:0] grp_fu_4266_p_opcode;
input  [31:0] grp_fu_4266_p_dout0;
output   grp_fu_4266_p_ce;
output  [31:0] grp_fu_2057_p_din0;
output  [31:0] grp_fu_2057_p_din1;
input  [31:0] grp_fu_2057_p_dout0;
output   grp_fu_2057_p_ce;
output  [31:0] grp_fu_4270_p_din0;
output  [31:0] grp_fu_4270_p_din1;
input  [31:0] grp_fu_4270_p_dout0;
output   grp_fu_4270_p_ce;
output  [31:0] grp_fu_4274_p_din0;
output  [31:0] grp_fu_4274_p_din1;
input  [31:0] grp_fu_4274_p_dout0;
output   grp_fu_4274_p_ce;
output  [31:0] grp_fu_4278_p_din0;
output  [31:0] grp_fu_4278_p_din1;
input  [31:0] grp_fu_4278_p_dout0;
output   grp_fu_4278_p_ce;
output  [31:0] grp_fu_4282_p_din0;
input  [31:0] grp_fu_4282_p_dout0;
output   grp_fu_4282_p_ce;
output  [31:0] grp_fu_4285_p_din0;
input  [31:0] grp_fu_4285_p_dout0;
output   grp_fu_4285_p_ce;
output  [31:0] grp_fu_4288_p_din0;
input  [31:0] grp_fu_4288_p_dout0;
output   grp_fu_4288_p_ce;
output  [31:0] grp_fu_4291_p_din0;
input  [31:0] grp_fu_4291_p_dout0;
output   grp_fu_4291_p_ce;
output  [31:0] grp_fu_2067_p_din0;
output  [31:0] grp_fu_2067_p_din1;
output  [4:0] grp_fu_2067_p_opcode;
input  [0:0] grp_fu_2067_p_dout0;
output   grp_fu_2067_p_ce;
output  [31:0] grp_fu_2072_p_din0;
output  [31:0] grp_fu_2072_p_din1;
output  [4:0] grp_fu_2072_p_opcode;
input  [0:0] grp_fu_2072_p_dout0;
output   grp_fu_2072_p_ce;

reg ap_idle;
reg h_a_ce0;
reg h_a_we0;
reg h_a_1_ce0;
reg h_a_1_we0;
reg h_a_2_ce0;
reg h_a_2_we0;
reg h_a_3_ce0;
reg h_a_3_we0;
reg h_a_4_ce0;
reg h_a_4_we0;
reg h_a_5_ce0;
reg h_a_5_we0;
reg h_a_6_ce0;
reg h_a_6_we0;
reg h_a_7_ce0;
reg h_a_7_we0;
reg h_a_8_ce0;
reg h_a_8_we0;
reg h_a_9_ce0;
reg h_a_9_we0;
reg h_a_10_ce0;
reg h_a_10_we0;
reg h_a_11_ce0;
reg h_a_11_we0;
reg h_a_12_ce0;
reg h_a_12_we0;
reg h_a_13_ce0;
reg h_a_13_we0;
reg h_a_14_ce0;
reg h_a_14_we0;
reg h_a_15_ce0;
reg h_a_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_enable_reg_pp0_iter49;
reg    ap_enable_reg_pp0_iter50;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_state48_pp0_stage0_iter47;
wire    ap_block_state49_pp0_stage0_iter48;
wire    ap_block_state50_pp0_stage0_iter49;
wire    ap_block_state51_pp0_stage0_iter50;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln112_fu_581_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] p_ZL16trunk_0_weight_q_0_address0;
reg    p_ZL16trunk_0_weight_q_0_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_0_q0;
wire   [8:0] p_ZL16trunk_0_weight_q_1_address0;
reg    p_ZL16trunk_0_weight_q_1_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_1_q0;
wire   [8:0] p_ZL16trunk_0_weight_q_2_address0;
reg    p_ZL16trunk_0_weight_q_2_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_2_q0;
wire   [8:0] p_ZL16trunk_0_weight_q_3_address0;
reg    p_ZL16trunk_0_weight_q_3_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_3_q0;
wire   [8:0] p_ZL16trunk_0_weight_q_4_address0;
reg    p_ZL16trunk_0_weight_q_4_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_4_q0;
wire   [8:0] p_ZL16trunk_0_weight_q_5_address0;
reg    p_ZL16trunk_0_weight_q_5_ce0;
wire   [7:0] p_ZL16trunk_0_weight_q_5_q0;
wire   [8:0] trunk_0_bias_address0;
reg    trunk_0_bias_ce0;
wire   [31:0] trunk_0_bias_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln112_fu_593_p1;
reg   [63:0] zext_ln112_reg_797;
reg   [63:0] zext_ln112_reg_797_pp0_iter1_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter2_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter3_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter4_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter5_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter6_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter7_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter8_reg;
reg   [63:0] zext_ln112_reg_797_pp0_iter9_reg;
reg   [4:0] lshr_ln_reg_812;
reg   [4:0] lshr_ln_reg_812_pp0_iter1_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter2_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter3_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter4_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter5_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter6_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter7_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter8_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter9_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter10_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter11_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter12_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter13_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter14_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter15_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter16_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter17_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter18_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter19_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter20_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter21_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter22_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter23_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter24_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter25_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter26_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter27_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter28_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter29_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter30_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter31_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter32_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter33_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter34_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter35_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter36_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter37_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter38_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter39_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter40_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter41_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter42_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter43_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter44_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter45_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter46_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter47_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter48_reg;
reg   [4:0] lshr_ln_reg_812_pp0_iter49_reg;
wire   [3:0] trunc_ln120_fu_608_p1;
reg   [3:0] trunc_ln120_reg_817;
reg   [3:0] trunc_ln120_reg_817_pp0_iter1_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter2_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter3_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter4_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter5_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter6_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter7_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter8_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter9_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter10_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter11_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter12_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter13_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter14_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter15_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter16_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter17_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter18_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter19_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter20_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter21_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter22_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter23_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter24_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter25_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter26_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter27_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter28_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter29_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter30_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter31_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter32_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter33_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter34_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter35_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter36_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter37_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter38_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter39_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter40_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter41_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter42_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter43_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter44_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter45_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter46_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter47_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter48_reg;
reg   [3:0] trunc_ln120_reg_817_pp0_iter49_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_0_load_reg_821;
wire  signed [31:0] sext_ln118_fu_617_p1;
reg   [31:0] conv1_reg_831;
reg   [7:0] p_ZL16trunk_0_weight_q_1_load_reg_841;
wire  signed [31:0] sext_ln118_1_fu_621_p1;
reg   [31:0] mul_reg_851;
reg   [31:0] conv29_1_reg_856;
reg   [7:0] p_ZL16trunk_0_weight_q_2_load_reg_886;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter12_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter13_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter14_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter15_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter16_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter12_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter13_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter14_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter15_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter16_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter17_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter18_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter19_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter20_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter21_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter12_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter13_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter14_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter15_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter16_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter17_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter18_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter19_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter20_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter21_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter22_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter23_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter24_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter25_reg;
reg   [7:0] p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter26_reg;
reg   [31:0] trunk_0_bias_load_reg_906;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter12_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter13_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter14_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter15_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter16_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter17_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter18_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter19_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter20_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter21_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter22_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter23_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter24_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter25_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter26_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter27_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter28_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter29_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter30_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter31_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter32_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter33_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter34_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter35_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter36_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter37_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter38_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter39_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter40_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter41_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter42_reg;
reg   [31:0] trunk_0_bias_load_reg_906_pp0_iter43_reg;
wire  signed [31:0] sext_ln118_2_fu_625_p1;
reg   [31:0] sum_reg_916;
reg   [31:0] mul32_1_reg_921;
reg   [31:0] conv29_2_reg_926;
wire  signed [31:0] sext_ln118_3_fu_629_p1;
reg   [31:0] sum_1_reg_936;
reg   [31:0] mul32_2_reg_941;
reg   [31:0] conv29_3_reg_946;
reg   [31:0] sum_2_reg_956;
reg   [31:0] mul32_3_reg_961;
wire   [31:0] grp_fu_557_p1;
reg   [31:0] conv29_4_reg_966;
reg   [31:0] sum_3_reg_976;
wire   [31:0] grp_fu_532_p2;
reg   [31:0] mul32_4_reg_981;
wire   [31:0] grp_fu_560_p1;
reg   [31:0] conv29_5_reg_986;
wire   [31:0] grp_fu_504_p2;
reg   [31:0] sum_4_reg_991;
wire   [31:0] grp_fu_536_p2;
reg   [31:0] mul32_5_reg_996;
wire   [31:0] grp_fu_508_p2;
reg   [31:0] sum_5_reg_1001;
wire   [31:0] grp_fu_540_p2;
reg   [31:0] mul1_reg_1006;
wire   [31:0] grp_fu_512_p2;
reg   [31:0] x_assign_reg_1011;
reg   [31:0] x_assign_reg_1011_pp0_iter49_reg;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln120_fu_737_p1;
reg   [9:0] i_2_fu_148;
wire   [9:0] add_ln112_fu_587_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i;
wire   [31:0] select_ln30_1_fu_714_p3;
wire  signed [31:0] grp_fu_557_p0;
wire  signed [31:0] grp_fu_560_p0;
wire   [31:0] bitcast_ln29_fu_641_p1;
wire   [7:0] tmp_1_fu_644_p4;
wire   [22:0] trunc_ln29_fu_654_p1;
wire   [0:0] icmp_ln29_1_fu_664_p2;
wire   [0:0] icmp_ln29_fu_658_p2;
wire   [0:0] or_ln29_fu_670_p2;
wire   [0:0] and_ln29_fu_676_p2;
wire   [0:0] and_ln30_fu_682_p2;
wire   [0:0] xor_ln29_fu_688_p2;
wire   [0:0] and_ln30_1_fu_694_p2;
wire   [0:0] or_ln30_fu_708_p2;
wire   [31:0] select_ln30_fu_700_p3;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg    ap_loop_exit_ready_pp0_iter48_reg;
reg    ap_loop_exit_ready_pp0_iter49_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 ap_enable_reg_pp0_iter49 = 1'b0;
#0 ap_enable_reg_pp0_iter50 = 1'b0;
#0 ap_done_reg = 1'b0;
end

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_0_address0),
    .ce0(p_ZL16trunk_0_weight_q_0_ce0),
    .q0(p_ZL16trunk_0_weight_q_0_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_1_address0),
    .ce0(p_ZL16trunk_0_weight_q_1_ce0),
    .q0(p_ZL16trunk_0_weight_q_1_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_2_address0),
    .ce0(p_ZL16trunk_0_weight_q_2_ce0),
    .q0(p_ZL16trunk_0_weight_q_2_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_3_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_3_address0),
    .ce0(p_ZL16trunk_0_weight_q_3_ce0),
    .q0(p_ZL16trunk_0_weight_q_3_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_4_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_4_address0),
    .ce0(p_ZL16trunk_0_weight_q_4_ce0),
    .q0(p_ZL16trunk_0_weight_q_4_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_5_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
p_ZL16trunk_0_weight_q_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16trunk_0_weight_q_5_address0),
    .ce0(p_ZL16trunk_0_weight_q_5_ce0),
    .q0(p_ZL16trunk_0_weight_q_5_q0)
);

pb_predict_pb_predict_Pipeline_LAYER0_trunk_0_bias_ROM_1P_LUTRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
trunk_0_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(trunk_0_bias_address0),
    .ce0(trunk_0_bias_ce0),
    .q0(trunk_0_bias_q0)
);

pb_predict_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_3_reg_976),
    .din1(mul32_4_reg_981),
    .ce(1'b1),
    .dout(grp_fu_504_p2)
);

pb_predict_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_reg_991),
    .din1(mul32_5_reg_996),
    .ce(1'b1),
    .dout(grp_fu_508_p2)
);

pb_predict_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul1_reg_1006),
    .din1(trunk_0_bias_load_reg_906_pp0_iter43_reg),
    .ce(1'b1),
    .dout(grp_fu_512_p2)
);

pb_predict_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv29_4_reg_966),
    .din1(input_scaled_4_reload),
    .ce(1'b1),
    .dout(grp_fu_532_p2)
);

pb_predict_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv29_5_reg_986),
    .din1(input_scaled_5_reload),
    .ce(1'b1),
    .dout(grp_fu_536_p2)
);

pb_predict_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_5_reg_1001),
    .din1(32'd1004497488),
    .ce(1'b1),
    .dout(grp_fu_540_p2)
);

pb_predict_sitofp_32s_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_4_no_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_557_p0),
    .ce(1'b1),
    .dout(grp_fu_557_p1)
);

pb_predict_sitofp_32s_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_4_no_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_560_p0),
    .ce(1'b1),
    .dout(grp_fu_560_p1)
);

pb_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter49_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter49 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter49 <= ap_enable_reg_pp0_iter48;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter50 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter50 <= ap_enable_reg_pp0_iter49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln112_fu_581_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_148 <= add_ln112_fu_587_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_148 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
        ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv1_reg_831 <= grp_fu_4282_p_dout0;
        conv29_1_reg_856 <= grp_fu_4285_p_dout0;
        conv29_2_reg_926 <= grp_fu_4288_p_dout0;
        conv29_3_reg_946 <= grp_fu_4291_p_dout0;
        conv29_4_reg_966 <= grp_fu_557_p1;
        conv29_5_reg_986 <= grp_fu_560_p1;
        lshr_ln_reg_812_pp0_iter10_reg <= lshr_ln_reg_812_pp0_iter9_reg;
        lshr_ln_reg_812_pp0_iter11_reg <= lshr_ln_reg_812_pp0_iter10_reg;
        lshr_ln_reg_812_pp0_iter12_reg <= lshr_ln_reg_812_pp0_iter11_reg;
        lshr_ln_reg_812_pp0_iter13_reg <= lshr_ln_reg_812_pp0_iter12_reg;
        lshr_ln_reg_812_pp0_iter14_reg <= lshr_ln_reg_812_pp0_iter13_reg;
        lshr_ln_reg_812_pp0_iter15_reg <= lshr_ln_reg_812_pp0_iter14_reg;
        lshr_ln_reg_812_pp0_iter16_reg <= lshr_ln_reg_812_pp0_iter15_reg;
        lshr_ln_reg_812_pp0_iter17_reg <= lshr_ln_reg_812_pp0_iter16_reg;
        lshr_ln_reg_812_pp0_iter18_reg <= lshr_ln_reg_812_pp0_iter17_reg;
        lshr_ln_reg_812_pp0_iter19_reg <= lshr_ln_reg_812_pp0_iter18_reg;
        lshr_ln_reg_812_pp0_iter20_reg <= lshr_ln_reg_812_pp0_iter19_reg;
        lshr_ln_reg_812_pp0_iter21_reg <= lshr_ln_reg_812_pp0_iter20_reg;
        lshr_ln_reg_812_pp0_iter22_reg <= lshr_ln_reg_812_pp0_iter21_reg;
        lshr_ln_reg_812_pp0_iter23_reg <= lshr_ln_reg_812_pp0_iter22_reg;
        lshr_ln_reg_812_pp0_iter24_reg <= lshr_ln_reg_812_pp0_iter23_reg;
        lshr_ln_reg_812_pp0_iter25_reg <= lshr_ln_reg_812_pp0_iter24_reg;
        lshr_ln_reg_812_pp0_iter26_reg <= lshr_ln_reg_812_pp0_iter25_reg;
        lshr_ln_reg_812_pp0_iter27_reg <= lshr_ln_reg_812_pp0_iter26_reg;
        lshr_ln_reg_812_pp0_iter28_reg <= lshr_ln_reg_812_pp0_iter27_reg;
        lshr_ln_reg_812_pp0_iter29_reg <= lshr_ln_reg_812_pp0_iter28_reg;
        lshr_ln_reg_812_pp0_iter2_reg <= lshr_ln_reg_812_pp0_iter1_reg;
        lshr_ln_reg_812_pp0_iter30_reg <= lshr_ln_reg_812_pp0_iter29_reg;
        lshr_ln_reg_812_pp0_iter31_reg <= lshr_ln_reg_812_pp0_iter30_reg;
        lshr_ln_reg_812_pp0_iter32_reg <= lshr_ln_reg_812_pp0_iter31_reg;
        lshr_ln_reg_812_pp0_iter33_reg <= lshr_ln_reg_812_pp0_iter32_reg;
        lshr_ln_reg_812_pp0_iter34_reg <= lshr_ln_reg_812_pp0_iter33_reg;
        lshr_ln_reg_812_pp0_iter35_reg <= lshr_ln_reg_812_pp0_iter34_reg;
        lshr_ln_reg_812_pp0_iter36_reg <= lshr_ln_reg_812_pp0_iter35_reg;
        lshr_ln_reg_812_pp0_iter37_reg <= lshr_ln_reg_812_pp0_iter36_reg;
        lshr_ln_reg_812_pp0_iter38_reg <= lshr_ln_reg_812_pp0_iter37_reg;
        lshr_ln_reg_812_pp0_iter39_reg <= lshr_ln_reg_812_pp0_iter38_reg;
        lshr_ln_reg_812_pp0_iter3_reg <= lshr_ln_reg_812_pp0_iter2_reg;
        lshr_ln_reg_812_pp0_iter40_reg <= lshr_ln_reg_812_pp0_iter39_reg;
        lshr_ln_reg_812_pp0_iter41_reg <= lshr_ln_reg_812_pp0_iter40_reg;
        lshr_ln_reg_812_pp0_iter42_reg <= lshr_ln_reg_812_pp0_iter41_reg;
        lshr_ln_reg_812_pp0_iter43_reg <= lshr_ln_reg_812_pp0_iter42_reg;
        lshr_ln_reg_812_pp0_iter44_reg <= lshr_ln_reg_812_pp0_iter43_reg;
        lshr_ln_reg_812_pp0_iter45_reg <= lshr_ln_reg_812_pp0_iter44_reg;
        lshr_ln_reg_812_pp0_iter46_reg <= lshr_ln_reg_812_pp0_iter45_reg;
        lshr_ln_reg_812_pp0_iter47_reg <= lshr_ln_reg_812_pp0_iter46_reg;
        lshr_ln_reg_812_pp0_iter48_reg <= lshr_ln_reg_812_pp0_iter47_reg;
        lshr_ln_reg_812_pp0_iter49_reg <= lshr_ln_reg_812_pp0_iter48_reg;
        lshr_ln_reg_812_pp0_iter4_reg <= lshr_ln_reg_812_pp0_iter3_reg;
        lshr_ln_reg_812_pp0_iter5_reg <= lshr_ln_reg_812_pp0_iter4_reg;
        lshr_ln_reg_812_pp0_iter6_reg <= lshr_ln_reg_812_pp0_iter5_reg;
        lshr_ln_reg_812_pp0_iter7_reg <= lshr_ln_reg_812_pp0_iter6_reg;
        lshr_ln_reg_812_pp0_iter8_reg <= lshr_ln_reg_812_pp0_iter7_reg;
        lshr_ln_reg_812_pp0_iter9_reg <= lshr_ln_reg_812_pp0_iter8_reg;
        mul1_reg_1006 <= grp_fu_540_p2;
        mul32_1_reg_921 <= grp_fu_4270_p_dout0;
        mul32_2_reg_941 <= grp_fu_4274_p_dout0;
        mul32_3_reg_961 <= grp_fu_4278_p_dout0;
        mul32_4_reg_981 <= grp_fu_532_p2;
        mul32_5_reg_996 <= grp_fu_536_p2;
        mul_reg_851 <= grp_fu_2057_p_dout0;
        p_ZL16trunk_0_weight_q_1_load_reg_841 <= p_ZL16trunk_0_weight_q_1_q0;
        p_ZL16trunk_0_weight_q_2_load_reg_886 <= p_ZL16trunk_0_weight_q_2_q0;
        p_ZL16trunk_0_weight_q_3_load_reg_891 <= p_ZL16trunk_0_weight_q_3_q0;
        p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter12_reg <= p_ZL16trunk_0_weight_q_3_load_reg_891;
        p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter13_reg <= p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter12_reg;
        p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter14_reg <= p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter13_reg;
        p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter15_reg <= p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter14_reg;
        p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter16_reg <= p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter15_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896 <= p_ZL16trunk_0_weight_q_4_q0;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter12_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter13_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter12_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter14_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter13_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter15_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter14_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter16_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter15_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter17_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter16_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter18_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter17_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter19_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter18_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter20_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter19_reg;
        p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter21_reg <= p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter20_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901 <= p_ZL16trunk_0_weight_q_5_q0;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter12_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter13_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter12_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter14_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter13_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter15_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter14_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter16_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter15_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter17_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter16_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter18_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter17_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter19_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter18_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter20_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter19_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter21_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter20_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter22_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter21_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter23_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter22_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter24_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter23_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter25_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter24_reg;
        p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter26_reg <= p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter25_reg;
        sum_1_reg_936 <= grp_fu_4258_p_dout0;
        sum_2_reg_956 <= grp_fu_4262_p_dout0;
        sum_3_reg_976 <= grp_fu_4266_p_dout0;
        sum_4_reg_991 <= grp_fu_504_p2;
        sum_5_reg_1001 <= grp_fu_508_p2;
        sum_reg_916 <= grp_fu_2052_p_dout0;
        trunc_ln120_reg_817_pp0_iter10_reg <= trunc_ln120_reg_817_pp0_iter9_reg;
        trunc_ln120_reg_817_pp0_iter11_reg <= trunc_ln120_reg_817_pp0_iter10_reg;
        trunc_ln120_reg_817_pp0_iter12_reg <= trunc_ln120_reg_817_pp0_iter11_reg;
        trunc_ln120_reg_817_pp0_iter13_reg <= trunc_ln120_reg_817_pp0_iter12_reg;
        trunc_ln120_reg_817_pp0_iter14_reg <= trunc_ln120_reg_817_pp0_iter13_reg;
        trunc_ln120_reg_817_pp0_iter15_reg <= trunc_ln120_reg_817_pp0_iter14_reg;
        trunc_ln120_reg_817_pp0_iter16_reg <= trunc_ln120_reg_817_pp0_iter15_reg;
        trunc_ln120_reg_817_pp0_iter17_reg <= trunc_ln120_reg_817_pp0_iter16_reg;
        trunc_ln120_reg_817_pp0_iter18_reg <= trunc_ln120_reg_817_pp0_iter17_reg;
        trunc_ln120_reg_817_pp0_iter19_reg <= trunc_ln120_reg_817_pp0_iter18_reg;
        trunc_ln120_reg_817_pp0_iter20_reg <= trunc_ln120_reg_817_pp0_iter19_reg;
        trunc_ln120_reg_817_pp0_iter21_reg <= trunc_ln120_reg_817_pp0_iter20_reg;
        trunc_ln120_reg_817_pp0_iter22_reg <= trunc_ln120_reg_817_pp0_iter21_reg;
        trunc_ln120_reg_817_pp0_iter23_reg <= trunc_ln120_reg_817_pp0_iter22_reg;
        trunc_ln120_reg_817_pp0_iter24_reg <= trunc_ln120_reg_817_pp0_iter23_reg;
        trunc_ln120_reg_817_pp0_iter25_reg <= trunc_ln120_reg_817_pp0_iter24_reg;
        trunc_ln120_reg_817_pp0_iter26_reg <= trunc_ln120_reg_817_pp0_iter25_reg;
        trunc_ln120_reg_817_pp0_iter27_reg <= trunc_ln120_reg_817_pp0_iter26_reg;
        trunc_ln120_reg_817_pp0_iter28_reg <= trunc_ln120_reg_817_pp0_iter27_reg;
        trunc_ln120_reg_817_pp0_iter29_reg <= trunc_ln120_reg_817_pp0_iter28_reg;
        trunc_ln120_reg_817_pp0_iter2_reg <= trunc_ln120_reg_817_pp0_iter1_reg;
        trunc_ln120_reg_817_pp0_iter30_reg <= trunc_ln120_reg_817_pp0_iter29_reg;
        trunc_ln120_reg_817_pp0_iter31_reg <= trunc_ln120_reg_817_pp0_iter30_reg;
        trunc_ln120_reg_817_pp0_iter32_reg <= trunc_ln120_reg_817_pp0_iter31_reg;
        trunc_ln120_reg_817_pp0_iter33_reg <= trunc_ln120_reg_817_pp0_iter32_reg;
        trunc_ln120_reg_817_pp0_iter34_reg <= trunc_ln120_reg_817_pp0_iter33_reg;
        trunc_ln120_reg_817_pp0_iter35_reg <= trunc_ln120_reg_817_pp0_iter34_reg;
        trunc_ln120_reg_817_pp0_iter36_reg <= trunc_ln120_reg_817_pp0_iter35_reg;
        trunc_ln120_reg_817_pp0_iter37_reg <= trunc_ln120_reg_817_pp0_iter36_reg;
        trunc_ln120_reg_817_pp0_iter38_reg <= trunc_ln120_reg_817_pp0_iter37_reg;
        trunc_ln120_reg_817_pp0_iter39_reg <= trunc_ln120_reg_817_pp0_iter38_reg;
        trunc_ln120_reg_817_pp0_iter3_reg <= trunc_ln120_reg_817_pp0_iter2_reg;
        trunc_ln120_reg_817_pp0_iter40_reg <= trunc_ln120_reg_817_pp0_iter39_reg;
        trunc_ln120_reg_817_pp0_iter41_reg <= trunc_ln120_reg_817_pp0_iter40_reg;
        trunc_ln120_reg_817_pp0_iter42_reg <= trunc_ln120_reg_817_pp0_iter41_reg;
        trunc_ln120_reg_817_pp0_iter43_reg <= trunc_ln120_reg_817_pp0_iter42_reg;
        trunc_ln120_reg_817_pp0_iter44_reg <= trunc_ln120_reg_817_pp0_iter43_reg;
        trunc_ln120_reg_817_pp0_iter45_reg <= trunc_ln120_reg_817_pp0_iter44_reg;
        trunc_ln120_reg_817_pp0_iter46_reg <= trunc_ln120_reg_817_pp0_iter45_reg;
        trunc_ln120_reg_817_pp0_iter47_reg <= trunc_ln120_reg_817_pp0_iter46_reg;
        trunc_ln120_reg_817_pp0_iter48_reg <= trunc_ln120_reg_817_pp0_iter47_reg;
        trunc_ln120_reg_817_pp0_iter49_reg <= trunc_ln120_reg_817_pp0_iter48_reg;
        trunc_ln120_reg_817_pp0_iter4_reg <= trunc_ln120_reg_817_pp0_iter3_reg;
        trunc_ln120_reg_817_pp0_iter5_reg <= trunc_ln120_reg_817_pp0_iter4_reg;
        trunc_ln120_reg_817_pp0_iter6_reg <= trunc_ln120_reg_817_pp0_iter5_reg;
        trunc_ln120_reg_817_pp0_iter7_reg <= trunc_ln120_reg_817_pp0_iter6_reg;
        trunc_ln120_reg_817_pp0_iter8_reg <= trunc_ln120_reg_817_pp0_iter7_reg;
        trunc_ln120_reg_817_pp0_iter9_reg <= trunc_ln120_reg_817_pp0_iter8_reg;
        trunk_0_bias_load_reg_906 <= trunk_0_bias_q0;
        trunk_0_bias_load_reg_906_pp0_iter12_reg <= trunk_0_bias_load_reg_906;
        trunk_0_bias_load_reg_906_pp0_iter13_reg <= trunk_0_bias_load_reg_906_pp0_iter12_reg;
        trunk_0_bias_load_reg_906_pp0_iter14_reg <= trunk_0_bias_load_reg_906_pp0_iter13_reg;
        trunk_0_bias_load_reg_906_pp0_iter15_reg <= trunk_0_bias_load_reg_906_pp0_iter14_reg;
        trunk_0_bias_load_reg_906_pp0_iter16_reg <= trunk_0_bias_load_reg_906_pp0_iter15_reg;
        trunk_0_bias_load_reg_906_pp0_iter17_reg <= trunk_0_bias_load_reg_906_pp0_iter16_reg;
        trunk_0_bias_load_reg_906_pp0_iter18_reg <= trunk_0_bias_load_reg_906_pp0_iter17_reg;
        trunk_0_bias_load_reg_906_pp0_iter19_reg <= trunk_0_bias_load_reg_906_pp0_iter18_reg;
        trunk_0_bias_load_reg_906_pp0_iter20_reg <= trunk_0_bias_load_reg_906_pp0_iter19_reg;
        trunk_0_bias_load_reg_906_pp0_iter21_reg <= trunk_0_bias_load_reg_906_pp0_iter20_reg;
        trunk_0_bias_load_reg_906_pp0_iter22_reg <= trunk_0_bias_load_reg_906_pp0_iter21_reg;
        trunk_0_bias_load_reg_906_pp0_iter23_reg <= trunk_0_bias_load_reg_906_pp0_iter22_reg;
        trunk_0_bias_load_reg_906_pp0_iter24_reg <= trunk_0_bias_load_reg_906_pp0_iter23_reg;
        trunk_0_bias_load_reg_906_pp0_iter25_reg <= trunk_0_bias_load_reg_906_pp0_iter24_reg;
        trunk_0_bias_load_reg_906_pp0_iter26_reg <= trunk_0_bias_load_reg_906_pp0_iter25_reg;
        trunk_0_bias_load_reg_906_pp0_iter27_reg <= trunk_0_bias_load_reg_906_pp0_iter26_reg;
        trunk_0_bias_load_reg_906_pp0_iter28_reg <= trunk_0_bias_load_reg_906_pp0_iter27_reg;
        trunk_0_bias_load_reg_906_pp0_iter29_reg <= trunk_0_bias_load_reg_906_pp0_iter28_reg;
        trunk_0_bias_load_reg_906_pp0_iter30_reg <= trunk_0_bias_load_reg_906_pp0_iter29_reg;
        trunk_0_bias_load_reg_906_pp0_iter31_reg <= trunk_0_bias_load_reg_906_pp0_iter30_reg;
        trunk_0_bias_load_reg_906_pp0_iter32_reg <= trunk_0_bias_load_reg_906_pp0_iter31_reg;
        trunk_0_bias_load_reg_906_pp0_iter33_reg <= trunk_0_bias_load_reg_906_pp0_iter32_reg;
        trunk_0_bias_load_reg_906_pp0_iter34_reg <= trunk_0_bias_load_reg_906_pp0_iter33_reg;
        trunk_0_bias_load_reg_906_pp0_iter35_reg <= trunk_0_bias_load_reg_906_pp0_iter34_reg;
        trunk_0_bias_load_reg_906_pp0_iter36_reg <= trunk_0_bias_load_reg_906_pp0_iter35_reg;
        trunk_0_bias_load_reg_906_pp0_iter37_reg <= trunk_0_bias_load_reg_906_pp0_iter36_reg;
        trunk_0_bias_load_reg_906_pp0_iter38_reg <= trunk_0_bias_load_reg_906_pp0_iter37_reg;
        trunk_0_bias_load_reg_906_pp0_iter39_reg <= trunk_0_bias_load_reg_906_pp0_iter38_reg;
        trunk_0_bias_load_reg_906_pp0_iter40_reg <= trunk_0_bias_load_reg_906_pp0_iter39_reg;
        trunk_0_bias_load_reg_906_pp0_iter41_reg <= trunk_0_bias_load_reg_906_pp0_iter40_reg;
        trunk_0_bias_load_reg_906_pp0_iter42_reg <= trunk_0_bias_load_reg_906_pp0_iter41_reg;
        trunk_0_bias_load_reg_906_pp0_iter43_reg <= trunk_0_bias_load_reg_906_pp0_iter42_reg;
        x_assign_reg_1011 <= grp_fu_512_p2;
        x_assign_reg_1011_pp0_iter49_reg <= x_assign_reg_1011;
        zext_ln112_reg_797_pp0_iter2_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter1_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter3_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter2_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter4_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter3_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter5_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter4_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter6_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter5_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter7_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter6_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter8_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter7_reg[9 : 0];
        zext_ln112_reg_797_pp0_iter9_reg[9 : 0] <= zext_ln112_reg_797_pp0_iter8_reg[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln_reg_812_pp0_iter1_reg <= lshr_ln_reg_812;
        p_ZL16trunk_0_weight_q_0_load_reg_821 <= p_ZL16trunk_0_weight_q_0_q0;
        trunc_ln120_reg_817_pp0_iter1_reg <= trunc_ln120_reg_817;
        zext_ln112_reg_797_pp0_iter1_reg[9 : 0] <= zext_ln112_reg_797[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln112_fu_581_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_812 <= {{ap_sig_allocacmp_i[8:4]}};
        trunc_ln120_reg_817 <= trunc_ln120_fu_608_p1;
        zext_ln112_reg_797[9 : 0] <= zext_ln112_fu_593_p1[9 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln112_fu_581_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter49_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter50 == 1'b0) & (ap_enable_reg_pp0_iter49 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 10'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_10_ce0 = 1'b1;
    end else begin
        h_a_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_10_we0 = 1'b1;
    end else begin
        h_a_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_11_ce0 = 1'b1;
    end else begin
        h_a_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_11_we0 = 1'b1;
    end else begin
        h_a_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_12_ce0 = 1'b1;
    end else begin
        h_a_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_12_we0 = 1'b1;
    end else begin
        h_a_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_13_ce0 = 1'b1;
    end else begin
        h_a_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_13_we0 = 1'b1;
    end else begin
        h_a_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_14_ce0 = 1'b1;
    end else begin
        h_a_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_14_we0 = 1'b1;
    end else begin
        h_a_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_15_ce0 = 1'b1;
    end else begin
        h_a_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_15_we0 = 1'b1;
    end else begin
        h_a_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_1_ce0 = 1'b1;
    end else begin
        h_a_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_1_we0 = 1'b1;
    end else begin
        h_a_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_2_ce0 = 1'b1;
    end else begin
        h_a_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_2_we0 = 1'b1;
    end else begin
        h_a_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_3_ce0 = 1'b1;
    end else begin
        h_a_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_3_we0 = 1'b1;
    end else begin
        h_a_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_4_ce0 = 1'b1;
    end else begin
        h_a_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_4_we0 = 1'b1;
    end else begin
        h_a_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_5_ce0 = 1'b1;
    end else begin
        h_a_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_5_we0 = 1'b1;
    end else begin
        h_a_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_6_ce0 = 1'b1;
    end else begin
        h_a_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_6_we0 = 1'b1;
    end else begin
        h_a_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_7_ce0 = 1'b1;
    end else begin
        h_a_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_7_we0 = 1'b1;
    end else begin
        h_a_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_8_ce0 = 1'b1;
    end else begin
        h_a_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_8_we0 = 1'b1;
    end else begin
        h_a_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_9_ce0 = 1'b1;
    end else begin
        h_a_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_9_we0 = 1'b1;
    end else begin
        h_a_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_ce0 = 1'b1;
    end else begin
        h_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln120_reg_817_pp0_iter49_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter50 == 1'b1))) begin
        h_a_we0 = 1'b1;
    end else begin
        h_a_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16trunk_0_weight_q_0_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL16trunk_0_weight_q_1_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL16trunk_0_weight_q_2_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL16trunk_0_weight_q_3_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL16trunk_0_weight_q_4_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_ZL16trunk_0_weight_q_5_ce0 = 1'b1;
    end else begin
        p_ZL16trunk_0_weight_q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunk_0_bias_ce0 = 1'b1;
    end else begin
        trunk_0_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln112_fu_587_p2 = (ap_sig_allocacmp_i + 10'd1);

assign and_ln29_fu_676_p2 = (or_ln29_fu_670_p2 & grp_fu_2067_p_dout0);

assign and_ln30_1_fu_694_p2 = (xor_ln29_fu_688_p2 & and_ln30_fu_682_p2);

assign and_ln30_fu_682_p2 = (or_ln29_fu_670_p2 & grp_fu_2072_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter47 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage0_iter49 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage0_iter50 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln29_fu_641_p1 = x_assign_reg_1011_pp0_iter49_reg;

assign grp_fu_2052_p_ce = 1'b1;

assign grp_fu_2052_p_din0 = mul_reg_851;

assign grp_fu_2052_p_din1 = 32'd0;

assign grp_fu_2052_p_opcode = 2'd0;

assign grp_fu_2057_p_ce = 1'b1;

assign grp_fu_2057_p_din0 = conv1_reg_831;

assign grp_fu_2057_p_din1 = input_scaled_reload;

assign grp_fu_2067_p_ce = 1'b1;

assign grp_fu_2067_p_din0 = x_assign_reg_1011;

assign grp_fu_2067_p_din1 = 32'd0;

assign grp_fu_2067_p_opcode = 5'd4;

assign grp_fu_2072_p_ce = 1'b1;

assign grp_fu_2072_p_din0 = x_assign_reg_1011;

assign grp_fu_2072_p_din1 = 32'd1086324736;

assign grp_fu_2072_p_opcode = 5'd2;

assign grp_fu_4258_p_ce = 1'b1;

assign grp_fu_4258_p_din0 = sum_reg_916;

assign grp_fu_4258_p_din1 = mul32_1_reg_921;

assign grp_fu_4258_p_opcode = 2'd0;

assign grp_fu_4262_p_ce = 1'b1;

assign grp_fu_4262_p_din0 = sum_1_reg_936;

assign grp_fu_4262_p_din1 = mul32_2_reg_941;

assign grp_fu_4262_p_opcode = 2'd0;

assign grp_fu_4266_p_ce = 1'b1;

assign grp_fu_4266_p_din0 = sum_2_reg_956;

assign grp_fu_4266_p_din1 = mul32_3_reg_961;

assign grp_fu_4266_p_opcode = 2'd0;

assign grp_fu_4270_p_ce = 1'b1;

assign grp_fu_4270_p_din0 = conv29_1_reg_856;

assign grp_fu_4270_p_din1 = input_scaled_1_reload;

assign grp_fu_4274_p_ce = 1'b1;

assign grp_fu_4274_p_din0 = conv29_2_reg_926;

assign grp_fu_4274_p_din1 = input_scaled_2_reload;

assign grp_fu_4278_p_ce = 1'b1;

assign grp_fu_4278_p_din0 = conv29_3_reg_946;

assign grp_fu_4278_p_din1 = input_scaled_3_reload;

assign grp_fu_4282_p_ce = 1'b1;

assign grp_fu_4282_p_din0 = sext_ln118_fu_617_p1;

assign grp_fu_4285_p_ce = 1'b1;

assign grp_fu_4285_p_din0 = sext_ln118_1_fu_621_p1;

assign grp_fu_4288_p_ce = 1'b1;

assign grp_fu_4288_p_din0 = sext_ln118_2_fu_625_p1;

assign grp_fu_4291_p_ce = 1'b1;

assign grp_fu_4291_p_din0 = sext_ln118_3_fu_629_p1;

assign grp_fu_557_p0 = $signed(p_ZL16trunk_0_weight_q_4_load_reg_896_pp0_iter21_reg);

assign grp_fu_560_p0 = $signed(p_ZL16trunk_0_weight_q_5_load_reg_901_pp0_iter26_reg);

assign h_a_10_address0 = zext_ln120_fu_737_p1;

assign h_a_10_d0 = select_ln30_1_fu_714_p3;

assign h_a_11_address0 = zext_ln120_fu_737_p1;

assign h_a_11_d0 = select_ln30_1_fu_714_p3;

assign h_a_12_address0 = zext_ln120_fu_737_p1;

assign h_a_12_d0 = select_ln30_1_fu_714_p3;

assign h_a_13_address0 = zext_ln120_fu_737_p1;

assign h_a_13_d0 = select_ln30_1_fu_714_p3;

assign h_a_14_address0 = zext_ln120_fu_737_p1;

assign h_a_14_d0 = select_ln30_1_fu_714_p3;

assign h_a_15_address0 = zext_ln120_fu_737_p1;

assign h_a_15_d0 = select_ln30_1_fu_714_p3;

assign h_a_1_address0 = zext_ln120_fu_737_p1;

assign h_a_1_d0 = select_ln30_1_fu_714_p3;

assign h_a_2_address0 = zext_ln120_fu_737_p1;

assign h_a_2_d0 = select_ln30_1_fu_714_p3;

assign h_a_3_address0 = zext_ln120_fu_737_p1;

assign h_a_3_d0 = select_ln30_1_fu_714_p3;

assign h_a_4_address0 = zext_ln120_fu_737_p1;

assign h_a_4_d0 = select_ln30_1_fu_714_p3;

assign h_a_5_address0 = zext_ln120_fu_737_p1;

assign h_a_5_d0 = select_ln30_1_fu_714_p3;

assign h_a_6_address0 = zext_ln120_fu_737_p1;

assign h_a_6_d0 = select_ln30_1_fu_714_p3;

assign h_a_7_address0 = zext_ln120_fu_737_p1;

assign h_a_7_d0 = select_ln30_1_fu_714_p3;

assign h_a_8_address0 = zext_ln120_fu_737_p1;

assign h_a_8_d0 = select_ln30_1_fu_714_p3;

assign h_a_9_address0 = zext_ln120_fu_737_p1;

assign h_a_9_d0 = select_ln30_1_fu_714_p3;

assign h_a_address0 = zext_ln120_fu_737_p1;

assign h_a_d0 = select_ln30_1_fu_714_p3;

assign icmp_ln112_fu_581_p2 = ((ap_sig_allocacmp_i == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln29_1_fu_664_p2 = ((trunc_ln29_fu_654_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_658_p2 = ((tmp_1_fu_644_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln29_fu_670_p2 = (icmp_ln29_fu_658_p2 | icmp_ln29_1_fu_664_p2);

assign or_ln30_fu_708_p2 = (and_ln30_1_fu_694_p2 | and_ln29_fu_676_p2);

assign p_ZL16trunk_0_weight_q_0_address0 = zext_ln112_fu_593_p1;

assign p_ZL16trunk_0_weight_q_1_address0 = zext_ln112_reg_797_pp0_iter4_reg;

assign p_ZL16trunk_0_weight_q_2_address0 = zext_ln112_reg_797_pp0_iter9_reg;

assign p_ZL16trunk_0_weight_q_3_address0 = zext_ln112_reg_797_pp0_iter9_reg;

assign p_ZL16trunk_0_weight_q_4_address0 = zext_ln112_reg_797_pp0_iter9_reg;

assign p_ZL16trunk_0_weight_q_5_address0 = zext_ln112_reg_797_pp0_iter9_reg;

assign select_ln30_1_fu_714_p3 = ((or_ln30_fu_708_p2[0:0] == 1'b1) ? select_ln30_fu_700_p3 : x_assign_reg_1011_pp0_iter49_reg);

assign select_ln30_fu_700_p3 = ((and_ln30_1_fu_694_p2[0:0] == 1'b1) ? 32'd1086324736 : 32'd0);

assign sext_ln118_1_fu_621_p1 = $signed(p_ZL16trunk_0_weight_q_1_load_reg_841);

assign sext_ln118_2_fu_625_p1 = $signed(p_ZL16trunk_0_weight_q_2_load_reg_886);

assign sext_ln118_3_fu_629_p1 = $signed(p_ZL16trunk_0_weight_q_3_load_reg_891_pp0_iter16_reg);

assign sext_ln118_fu_617_p1 = $signed(p_ZL16trunk_0_weight_q_0_load_reg_821);

assign tmp_1_fu_644_p4 = {{bitcast_ln29_fu_641_p1[30:23]}};

assign trunc_ln120_fu_608_p1 = ap_sig_allocacmp_i[3:0];

assign trunc_ln29_fu_654_p1 = bitcast_ln29_fu_641_p1[22:0];

assign trunk_0_bias_address0 = zext_ln112_reg_797_pp0_iter9_reg;

assign xor_ln29_fu_688_p2 = (1'd1 ^ and_ln29_fu_676_p2);

assign zext_ln112_fu_593_p1 = ap_sig_allocacmp_i;

assign zext_ln120_fu_737_p1 = lshr_ln_reg_812_pp0_iter49_reg;

always @ (posedge ap_clk) begin
    zext_ln112_reg_797[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter1_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter2_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter4_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter5_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter6_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter7_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter8_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln112_reg_797_pp0_iter9_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //pb_predict_pb_predict_Pipeline_LAYER0
