set SynModuleInfo {
  {SRCNAME pb_predict_Pipeline_READ_INPUT MODELNAME pb_predict_Pipeline_READ_INPUT RTLNAME pb_predict_pb_predict_Pipeline_READ_INPUT
    SUBMODULES {
      {MODELNAME pb_predict_flow_control_loop_pipe_sequential_init RTLNAME pb_predict_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME pb_predict_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME pb_predict_Pipeline_SCALE_INPUT MODELNAME pb_predict_Pipeline_SCALE_INPUT RTLNAME pb_predict_pb_predict_Pipeline_SCALE_INPUT
    SUBMODULES {
      {MODELNAME pb_predict_fdiv_32ns_32ns_32_10_no_dsp_1 RTLNAME pb_predict_fdiv_32ns_32ns_32_10_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 9 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_mux_63_32_1_1 RTLNAME pb_predict_mux_63_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_mean_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_mean_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_scale_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_scale_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_LAYER0 MODELNAME pb_predict_Pipeline_LAYER0 RTLNAME pb_predict_pb_predict_Pipeline_LAYER0
    SUBMODULES {
      {MODELNAME pb_predict_fadd_32ns_32ns_32_5_full_dsp_1 RTLNAME pb_predict_fadd_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME pb_predict_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_sitofp_32s_32_4_no_dsp_1 RTLNAME pb_predict_sitofp_32s_32_4_no_dsp_1 BINDTYPE op TYPE sitofp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_0_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_0_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_1_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_1_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_2_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_2_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_3_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_3_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_4_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_4_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_5_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_p_ZL16trunk_0_weight_q_5_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_LAYER0_trunk_0_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_LAYER0_trunk_0_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_L1_MAC MODELNAME pb_predict_Pipeline_L1_MAC RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC
    SUBMODULES {
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_0_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_0_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_1_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_1_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_2_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_2_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_3_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_3_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_4_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_4_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_5_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_5_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_6_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_6_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_7_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_7_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_8_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_8_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_9_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_9_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_10_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_10_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_11_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_11_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_12_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_12_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_13_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_13_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_14_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_14_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_15_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_L1_MAC_p_ZL16trunk_1_weight_q_15_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_REG_H0_MAC MODELNAME pb_predict_Pipeline_REG_H0_MAC RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC
    SUBMODULES {
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_0_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_0_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_1_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_1_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_2_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_2_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_3_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_3_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_4_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_4_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_5_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_5_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_6_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_6_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_7_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_7_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_8_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_8_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_9_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_9_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_10_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_10_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_11_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_11_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_12_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_12_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_13_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_13_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_14_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_14_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_15_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H0_MAC_p_ZL19reg_head_0_weight_q_15_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_REG_H1_MAC MODELNAME pb_predict_Pipeline_REG_H1_MAC RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC
    SUBMODULES {
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_0_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_0_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_1_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_1_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_2_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_2_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_3_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_3_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_4_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_4_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_5_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_5_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_6_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_6_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_7_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_7_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_8_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_8_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_9_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_9_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_10_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_10_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_11_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_11_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_12_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_12_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_13_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_13_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_14_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_14_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_15_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_15_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_CLS_H0_MAC MODELNAME pb_predict_Pipeline_CLS_H0_MAC RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC
    SUBMODULES {
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_0_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_0_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_1_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_1_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_2_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_2_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_3_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_3_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_4_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_4_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_5_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_5_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_6_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_6_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_7_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_7_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_8_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_8_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_9_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_9_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_10_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_10_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_11_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_11_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_12_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_12_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_13_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_13_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_14_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_14_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_15_ROM_2P_BRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H0_MAC_p_ZL19cls_head_0_weight_q_15_ROM_2P_BRAM_1R BINDTYPE storage TYPE rom_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_CLS_H1_MAC MODELNAME pb_predict_Pipeline_CLS_H1_MAC RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC
    SUBMODULES {
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_0_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_0_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_1_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_1_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_2_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_2_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_3_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_3_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_4_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_4_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_5_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_5_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_6_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_6_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_7_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_7_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_8_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_8_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_9_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_9_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_10_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_10_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_11_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_11_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_12_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_12_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_13_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_13_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_14_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_14_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_15_ROM_1P_LUTRAM_1R RTLNAME pb_predict_pb_predict_Pipeline_CLS_H1_MAC_p_ZL19cls_head_1_weight_q_15_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pb_predict_Pipeline_WRITE_REG MODELNAME pb_predict_Pipeline_WRITE_REG RTLNAME pb_predict_pb_predict_Pipeline_WRITE_REG}
  {SRCNAME pb_predict_Pipeline_WRITE_CLS MODELNAME pb_predict_Pipeline_WRITE_CLS RTLNAME pb_predict_pb_predict_Pipeline_WRITE_CLS}
  {SRCNAME pb_predict MODELNAME pb_predict RTLNAME pb_predict IS_TOP 1
    SUBMODULES {
      {MODELNAME pb_predict_faddfsub_32ns_32ns_32_5_full_dsp_1 RTLNAME pb_predict_faddfsub_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME pb_predict_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_trunk_1_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_trunk_1_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_reg_head_0_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_reg_head_0_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_reg_head_1_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_reg_head_1_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_y_scaler_scale_ROM_1P_LUTRAM_1R RTLNAME pb_predict_y_scaler_scale_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_y_scaler_mean_ROM_1P_LUTRAM_1R RTLNAME pb_predict_y_scaler_mean_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_cls_head_0_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_cls_head_0_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_cls_head_1_bias_ROM_1P_LUTRAM_1R RTLNAME pb_predict_cls_head_1_bias_ROM_1P_LUTRAM_1R BINDTYPE storage TYPE rom_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_h_a_RAM_AUTO_1R1W RTLNAME pb_predict_h_a_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_head_buf_RAM_AUTO_1R1W RTLNAME pb_predict_head_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pb_predict_control_s_axi RTLNAME pb_predict_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME pb_predict_regslice_both RTLNAME pb_predict_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME pb_predict_regslice_both_U}
    }
  }
}
