// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pb_predict_pb_predict_Pipeline_SCALE_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_raw_reload,
        input_raw_1_reload,
        input_raw_2_reload,
        input_raw_3_reload,
        input_raw_4_reload,
        input_raw_5_reload,
        input_scaled_5_out,
        input_scaled_5_out_ap_vld,
        input_scaled_4_out,
        input_scaled_4_out_ap_vld,
        input_scaled_3_out,
        input_scaled_3_out_ap_vld,
        input_scaled_2_out,
        input_scaled_2_out_ap_vld,
        input_scaled_1_out,
        input_scaled_1_out_ap_vld,
        input_scaled_out,
        input_scaled_out_ap_vld,
        grp_fu_2052_p_din0,
        grp_fu_2052_p_din1,
        grp_fu_2052_p_opcode,
        grp_fu_2052_p_dout0,
        grp_fu_2052_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] input_raw_reload;
input  [31:0] input_raw_1_reload;
input  [31:0] input_raw_2_reload;
input  [31:0] input_raw_3_reload;
input  [31:0] input_raw_4_reload;
input  [31:0] input_raw_5_reload;
output  [31:0] input_scaled_5_out;
output   input_scaled_5_out_ap_vld;
output  [31:0] input_scaled_4_out;
output   input_scaled_4_out_ap_vld;
output  [31:0] input_scaled_3_out;
output   input_scaled_3_out_ap_vld;
output  [31:0] input_scaled_2_out;
output   input_scaled_2_out_ap_vld;
output  [31:0] input_scaled_1_out;
output   input_scaled_1_out_ap_vld;
output  [31:0] input_scaled_out;
output   input_scaled_out_ap_vld;
output  [31:0] grp_fu_2052_p_din0;
output  [31:0] grp_fu_2052_p_din1;
output  [0:0] grp_fu_2052_p_opcode;
input  [31:0] grp_fu_2052_p_dout0;
output   grp_fu_2052_p_ce;

reg ap_idle;
reg input_scaled_5_out_ap_vld;
reg input_scaled_4_out_ap_vld;
reg input_scaled_3_out_ap_vld;
reg input_scaled_2_out_ap_vld;
reg input_scaled_1_out_ap_vld;
reg input_scaled_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln102_fu_221_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] x_scaler_mean_address0;
reg    x_scaler_mean_ce0;
wire   [31:0] x_scaler_mean_q0;
wire   [2:0] x_scaler_scale_address0;
reg    x_scaler_scale_ce0;
wire   [31:0] x_scaler_scale_q0;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] i_reg_383;
reg   [2:0] i_reg_383_pp0_iter1_reg;
reg   [2:0] i_reg_383_pp0_iter2_reg;
reg   [2:0] i_reg_383_pp0_iter3_reg;
reg   [2:0] i_reg_383_pp0_iter4_reg;
reg   [2:0] i_reg_383_pp0_iter5_reg;
reg   [2:0] i_reg_383_pp0_iter6_reg;
reg   [2:0] i_reg_383_pp0_iter7_reg;
reg   [2:0] i_reg_383_pp0_iter8_reg;
reg   [2:0] i_reg_383_pp0_iter9_reg;
reg   [2:0] i_reg_383_pp0_iter10_reg;
reg   [2:0] i_reg_383_pp0_iter11_reg;
reg   [2:0] i_reg_383_pp0_iter12_reg;
reg   [2:0] i_reg_383_pp0_iter13_reg;
reg   [2:0] i_reg_383_pp0_iter14_reg;
reg   [0:0] icmp_ln102_reg_388;
reg   [0:0] icmp_ln102_reg_388_pp0_iter1_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter2_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter3_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter4_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter5_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter6_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter7_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter8_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter9_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter10_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter11_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter12_reg;
reg   [0:0] icmp_ln102_reg_388_pp0_iter13_reg;
wire   [31:0] tmp_fu_244_p8;
reg   [31:0] x_scaler_scale_load_reg_412;
reg   [31:0] x_scaler_scale_load_reg_412_pp0_iter2_reg;
reg   [31:0] x_scaler_scale_load_reg_412_pp0_iter3_reg;
reg   [31:0] x_scaler_scale_load_reg_412_pp0_iter4_reg;
reg   [31:0] x_scaler_scale_load_reg_412_pp0_iter5_reg;
reg   [31:0] sub_reg_417;
wire   [63:0] zext_ln102_fu_233_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] i_1_fu_72;
wire   [2:0] add_ln102_fu_227_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i;
reg   [31:0] input_scaled_fu_76;
wire   [31:0] grp_fu_209_p2;
reg   [31:0] input_scaled_1_fu_80;
reg   [31:0] input_scaled_2_fu_84;
reg   [31:0] input_scaled_3_fu_88;
reg   [31:0] input_scaled_4_fu_92;
reg   [31:0] input_scaled_5_fu_96;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_done_reg = 1'b0;
end

pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_mean_ROM_1P_LUTRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
x_scaler_mean_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_scaler_mean_address0),
    .ce0(x_scaler_mean_ce0),
    .q0(x_scaler_mean_q0)
);

pb_predict_pb_predict_Pipeline_SCALE_INPUT_x_scaler_scale_ROM_1P_LUTRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
x_scaler_scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_scaler_scale_address0),
    .ce0(x_scaler_scale_ce0),
    .q0(x_scaler_scale_q0)
);

pb_predict_fdiv_32ns_32ns_32_10_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_10_no_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_417),
    .din1(x_scaler_scale_load_reg_412_pp0_iter5_reg),
    .ce(1'b1),
    .dout(grp_fu_209_p2)
);

pb_predict_mux_63_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_63_32_1_1_U13(
    .din0(input_raw_reload),
    .din1(input_raw_1_reload),
    .din2(input_raw_2_reload),
    .din3(input_raw_3_reload),
    .din4(input_raw_4_reload),
    .din5(input_raw_5_reload),
    .din6(i_reg_383),
    .dout(tmp_fu_244_p8)
);

pb_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln102_fu_221_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_72 <= add_ln102_fu_227_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_reg_383_pp0_iter10_reg <= i_reg_383_pp0_iter9_reg;
        i_reg_383_pp0_iter11_reg <= i_reg_383_pp0_iter10_reg;
        i_reg_383_pp0_iter12_reg <= i_reg_383_pp0_iter11_reg;
        i_reg_383_pp0_iter13_reg <= i_reg_383_pp0_iter12_reg;
        i_reg_383_pp0_iter14_reg <= i_reg_383_pp0_iter13_reg;
        i_reg_383_pp0_iter2_reg <= i_reg_383_pp0_iter1_reg;
        i_reg_383_pp0_iter3_reg <= i_reg_383_pp0_iter2_reg;
        i_reg_383_pp0_iter4_reg <= i_reg_383_pp0_iter3_reg;
        i_reg_383_pp0_iter5_reg <= i_reg_383_pp0_iter4_reg;
        i_reg_383_pp0_iter6_reg <= i_reg_383_pp0_iter5_reg;
        i_reg_383_pp0_iter7_reg <= i_reg_383_pp0_iter6_reg;
        i_reg_383_pp0_iter8_reg <= i_reg_383_pp0_iter7_reg;
        i_reg_383_pp0_iter9_reg <= i_reg_383_pp0_iter8_reg;
        icmp_ln102_reg_388_pp0_iter10_reg <= icmp_ln102_reg_388_pp0_iter9_reg;
        icmp_ln102_reg_388_pp0_iter11_reg <= icmp_ln102_reg_388_pp0_iter10_reg;
        icmp_ln102_reg_388_pp0_iter12_reg <= icmp_ln102_reg_388_pp0_iter11_reg;
        icmp_ln102_reg_388_pp0_iter13_reg <= icmp_ln102_reg_388_pp0_iter12_reg;
        icmp_ln102_reg_388_pp0_iter2_reg <= icmp_ln102_reg_388_pp0_iter1_reg;
        icmp_ln102_reg_388_pp0_iter3_reg <= icmp_ln102_reg_388_pp0_iter2_reg;
        icmp_ln102_reg_388_pp0_iter4_reg <= icmp_ln102_reg_388_pp0_iter3_reg;
        icmp_ln102_reg_388_pp0_iter5_reg <= icmp_ln102_reg_388_pp0_iter4_reg;
        icmp_ln102_reg_388_pp0_iter6_reg <= icmp_ln102_reg_388_pp0_iter5_reg;
        icmp_ln102_reg_388_pp0_iter7_reg <= icmp_ln102_reg_388_pp0_iter6_reg;
        icmp_ln102_reg_388_pp0_iter8_reg <= icmp_ln102_reg_388_pp0_iter7_reg;
        icmp_ln102_reg_388_pp0_iter9_reg <= icmp_ln102_reg_388_pp0_iter8_reg;
        sub_reg_417 <= grp_fu_2052_p_dout0;
        x_scaler_scale_load_reg_412_pp0_iter2_reg <= x_scaler_scale_load_reg_412;
        x_scaler_scale_load_reg_412_pp0_iter3_reg <= x_scaler_scale_load_reg_412_pp0_iter2_reg;
        x_scaler_scale_load_reg_412_pp0_iter4_reg <= x_scaler_scale_load_reg_412_pp0_iter3_reg;
        x_scaler_scale_load_reg_412_pp0_iter5_reg <= x_scaler_scale_load_reg_412_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_reg_383 <= ap_sig_allocacmp_i;
        i_reg_383_pp0_iter1_reg <= i_reg_383;
        icmp_ln102_reg_388 <= icmp_ln102_fu_221_p2;
        icmp_ln102_reg_388_pp0_iter1_reg <= icmp_ln102_reg_388;
        x_scaler_scale_load_reg_412 <= x_scaler_scale_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (i_reg_383_pp0_iter14_reg == 3'd1))) begin
        input_scaled_1_fu_80 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (i_reg_383_pp0_iter14_reg == 3'd2))) begin
        input_scaled_2_fu_84 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (i_reg_383_pp0_iter14_reg == 3'd3))) begin
        input_scaled_3_fu_88 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (i_reg_383_pp0_iter14_reg == 3'd4))) begin
        input_scaled_4_fu_92 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & ((i_reg_383_pp0_iter14_reg == 3'd5) | ((i_reg_383_pp0_iter14_reg == 3'd6) | (i_reg_383_pp0_iter14_reg == 3'd7))))) begin
        input_scaled_5_fu_96 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (i_reg_383_pp0_iter14_reg == 3'd0))) begin
        input_scaled_fu_76 <= grp_fu_209_p2;
    end
end

always @ (*) begin
    if (((icmp_ln102_fu_221_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 3'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_1_out_ap_vld = 1'b1;
    end else begin
        input_scaled_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_2_out_ap_vld = 1'b1;
    end else begin
        input_scaled_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_3_out_ap_vld = 1'b1;
    end else begin
        input_scaled_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_4_out_ap_vld = 1'b1;
    end else begin
        input_scaled_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_5_out_ap_vld = 1'b1;
    end else begin
        input_scaled_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln102_reg_388_pp0_iter13_reg == 1'd1))) begin
        input_scaled_out_ap_vld = 1'b1;
    end else begin
        input_scaled_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_scaler_mean_ce0 = 1'b1;
    end else begin
        x_scaler_mean_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_scaler_scale_ce0 = 1'b1;
    end else begin
        x_scaler_scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln102_fu_227_p2 = (ap_sig_allocacmp_i + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_2052_p_ce = 1'b1;

assign grp_fu_2052_p_din0 = tmp_fu_244_p8;

assign grp_fu_2052_p_din1 = x_scaler_mean_q0;

assign grp_fu_2052_p_opcode = 2'd1;

assign icmp_ln102_fu_221_p2 = ((ap_sig_allocacmp_i == 3'd6) ? 1'b1 : 1'b0);

assign input_scaled_1_out = input_scaled_1_fu_80;

assign input_scaled_2_out = input_scaled_2_fu_84;

assign input_scaled_3_out = input_scaled_3_fu_88;

assign input_scaled_4_out = input_scaled_4_fu_92;

assign input_scaled_5_out = input_scaled_5_fu_96;

assign input_scaled_out = input_scaled_fu_76;

assign x_scaler_mean_address0 = zext_ln102_fu_233_p1;

assign x_scaler_scale_address0 = zext_ln102_fu_233_p1;

assign zext_ln102_fu_233_p1 = ap_sig_allocacmp_i;

endmodule //pb_predict_pb_predict_Pipeline_SCALE_INPUT
