// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pb_predict_pb_predict_Pipeline_REG_H1_MAC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_5,
        head_buf_address0,
        head_buf_ce0,
        head_buf_q0,
        head_buf_1_address0,
        head_buf_1_ce0,
        head_buf_1_q0,
        head_buf_2_address0,
        head_buf_2_ce0,
        head_buf_2_q0,
        head_buf_3_address0,
        head_buf_3_ce0,
        head_buf_3_q0,
        head_buf_4_address0,
        head_buf_4_ce0,
        head_buf_4_q0,
        head_buf_5_address0,
        head_buf_5_ce0,
        head_buf_5_q0,
        head_buf_6_address0,
        head_buf_6_ce0,
        head_buf_6_q0,
        head_buf_7_address0,
        head_buf_7_ce0,
        head_buf_7_q0,
        head_buf_8_address0,
        head_buf_8_ce0,
        head_buf_8_q0,
        head_buf_9_address0,
        head_buf_9_ce0,
        head_buf_9_q0,
        head_buf_10_address0,
        head_buf_10_ce0,
        head_buf_10_q0,
        head_buf_11_address0,
        head_buf_11_ce0,
        head_buf_11_q0,
        head_buf_12_address0,
        head_buf_12_ce0,
        head_buf_12_q0,
        head_buf_13_address0,
        head_buf_13_ce0,
        head_buf_13_q0,
        head_buf_14_address0,
        head_buf_14_ce0,
        head_buf_14_q0,
        head_buf_15_address0,
        head_buf_15_ce0,
        head_buf_15_q0,
        s0_4_out,
        s0_4_out_ap_vld,
        s1_4_out,
        s1_4_out_ap_vld,
        s2_4_out,
        s2_4_out_ap_vld,
        s3_4_out,
        s3_4_out_ap_vld,
        s4_4_out,
        s4_4_out_ap_vld,
        s5_4_out,
        s5_4_out_ap_vld,
        s6_4_out,
        s6_4_out_ap_vld,
        s7_4_out,
        s7_4_out_ap_vld,
        s8_4_out,
        s8_4_out_ap_vld,
        s9_4_out,
        s9_4_out_ap_vld,
        s10_4_out,
        s10_4_out_ap_vld,
        s11_4_out,
        s11_4_out_ap_vld,
        s12_4_out,
        s12_4_out_ap_vld,
        s13_4_out,
        s13_4_out_ap_vld,
        s14_4_out,
        s14_4_out_ap_vld,
        s15_4_out,
        s15_4_out_ap_vld,
        grp_fu_2052_p_din0,
        grp_fu_2052_p_din1,
        grp_fu_2052_p_opcode,
        grp_fu_2052_p_dout0,
        grp_fu_2052_p_ce,
        grp_fu_4258_p_din0,
        grp_fu_4258_p_din1,
        grp_fu_4258_p_opcode,
        grp_fu_4258_p_dout0,
        grp_fu_4258_p_ce,
        grp_fu_4262_p_din0,
        grp_fu_4262_p_din1,
        grp_fu_4262_p_opcode,
        grp_fu_4262_p_dout0,
        grp_fu_4262_p_ce,
        grp_fu_4266_p_din0,
        grp_fu_4266_p_din1,
        grp_fu_4266_p_opcode,
        grp_fu_4266_p_dout0,
        grp_fu_4266_p_ce,
        grp_fu_2057_p_din0,
        grp_fu_2057_p_din1,
        grp_fu_2057_p_dout0,
        grp_fu_2057_p_ce,
        grp_fu_4270_p_din0,
        grp_fu_4270_p_din1,
        grp_fu_4270_p_dout0,
        grp_fu_4270_p_ce,
        grp_fu_4274_p_din0,
        grp_fu_4274_p_din1,
        grp_fu_4274_p_dout0,
        grp_fu_4274_p_ce,
        grp_fu_4278_p_din0,
        grp_fu_4278_p_din1,
        grp_fu_4278_p_dout0,
        grp_fu_4278_p_ce,
        grp_fu_4282_p_din0,
        grp_fu_4282_p_dout0,
        grp_fu_4282_p_ce,
        grp_fu_4285_p_din0,
        grp_fu_4285_p_dout0,
        grp_fu_4285_p_ce,
        grp_fu_4288_p_din0,
        grp_fu_4288_p_dout0,
        grp_fu_4288_p_ce,
        grp_fu_4291_p_din0,
        grp_fu_4291_p_dout0,
        grp_fu_4291_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] i_5;
output  [3:0] head_buf_address0;
output   head_buf_ce0;
input  [31:0] head_buf_q0;
output  [3:0] head_buf_1_address0;
output   head_buf_1_ce0;
input  [31:0] head_buf_1_q0;
output  [3:0] head_buf_2_address0;
output   head_buf_2_ce0;
input  [31:0] head_buf_2_q0;
output  [3:0] head_buf_3_address0;
output   head_buf_3_ce0;
input  [31:0] head_buf_3_q0;
output  [3:0] head_buf_4_address0;
output   head_buf_4_ce0;
input  [31:0] head_buf_4_q0;
output  [3:0] head_buf_5_address0;
output   head_buf_5_ce0;
input  [31:0] head_buf_5_q0;
output  [3:0] head_buf_6_address0;
output   head_buf_6_ce0;
input  [31:0] head_buf_6_q0;
output  [3:0] head_buf_7_address0;
output   head_buf_7_ce0;
input  [31:0] head_buf_7_q0;
output  [3:0] head_buf_8_address0;
output   head_buf_8_ce0;
input  [31:0] head_buf_8_q0;
output  [3:0] head_buf_9_address0;
output   head_buf_9_ce0;
input  [31:0] head_buf_9_q0;
output  [3:0] head_buf_10_address0;
output   head_buf_10_ce0;
input  [31:0] head_buf_10_q0;
output  [3:0] head_buf_11_address0;
output   head_buf_11_ce0;
input  [31:0] head_buf_11_q0;
output  [3:0] head_buf_12_address0;
output   head_buf_12_ce0;
input  [31:0] head_buf_12_q0;
output  [3:0] head_buf_13_address0;
output   head_buf_13_ce0;
input  [31:0] head_buf_13_q0;
output  [3:0] head_buf_14_address0;
output   head_buf_14_ce0;
input  [31:0] head_buf_14_q0;
output  [3:0] head_buf_15_address0;
output   head_buf_15_ce0;
input  [31:0] head_buf_15_q0;
output  [31:0] s0_4_out;
output   s0_4_out_ap_vld;
output  [31:0] s1_4_out;
output   s1_4_out_ap_vld;
output  [31:0] s2_4_out;
output   s2_4_out_ap_vld;
output  [31:0] s3_4_out;
output   s3_4_out_ap_vld;
output  [31:0] s4_4_out;
output   s4_4_out_ap_vld;
output  [31:0] s5_4_out;
output   s5_4_out_ap_vld;
output  [31:0] s6_4_out;
output   s6_4_out_ap_vld;
output  [31:0] s7_4_out;
output   s7_4_out_ap_vld;
output  [31:0] s8_4_out;
output   s8_4_out_ap_vld;
output  [31:0] s9_4_out;
output   s9_4_out_ap_vld;
output  [31:0] s10_4_out;
output   s10_4_out_ap_vld;
output  [31:0] s11_4_out;
output   s11_4_out_ap_vld;
output  [31:0] s12_4_out;
output   s12_4_out_ap_vld;
output  [31:0] s13_4_out;
output   s13_4_out_ap_vld;
output  [31:0] s14_4_out;
output   s14_4_out_ap_vld;
output  [31:0] s15_4_out;
output   s15_4_out_ap_vld;
output  [31:0] grp_fu_2052_p_din0;
output  [31:0] grp_fu_2052_p_din1;
output  [0:0] grp_fu_2052_p_opcode;
input  [31:0] grp_fu_2052_p_dout0;
output   grp_fu_2052_p_ce;
output  [31:0] grp_fu_4258_p_din0;
output  [31:0] grp_fu_4258_p_din1;
output  [1:0] grp_fu_4258_p_opcode;
input  [31:0] grp_fu_4258_p_dout0;
output   grp_fu_4258_p_ce;
output  [31:0] grp_fu_4262_p_din0;
output  [31:0] grp_fu_4262_p_din1;
output  [1:0] grp_fu_4262_p_opcode;
input  [31:0] grp_fu_4262_p_dout0;
output   grp_fu_4262_p_ce;
output  [31:0] grp_fu_4266_p_din0;
output  [31:0] grp_fu_4266_p_din1;
output  [1:0] grp_fu_4266_p_opcode;
input  [31:0] grp_fu_4266_p_dout0;
output   grp_fu_4266_p_ce;
output  [31:0] grp_fu_2057_p_din0;
output  [31:0] grp_fu_2057_p_din1;
input  [31:0] grp_fu_2057_p_dout0;
output   grp_fu_2057_p_ce;
output  [31:0] grp_fu_4270_p_din0;
output  [31:0] grp_fu_4270_p_din1;
input  [31:0] grp_fu_4270_p_dout0;
output   grp_fu_4270_p_ce;
output  [31:0] grp_fu_4274_p_din0;
output  [31:0] grp_fu_4274_p_din1;
input  [31:0] grp_fu_4274_p_dout0;
output   grp_fu_4274_p_ce;
output  [31:0] grp_fu_4278_p_din0;
output  [31:0] grp_fu_4278_p_din1;
input  [31:0] grp_fu_4278_p_dout0;
output   grp_fu_4278_p_ce;
output  [31:0] grp_fu_4282_p_din0;
input  [31:0] grp_fu_4282_p_dout0;
output   grp_fu_4282_p_ce;
output  [31:0] grp_fu_4285_p_din0;
input  [31:0] grp_fu_4285_p_dout0;
output   grp_fu_4285_p_ce;
output  [31:0] grp_fu_4288_p_din0;
input  [31:0] grp_fu_4288_p_dout0;
output   grp_fu_4288_p_ce;
output  [31:0] grp_fu_4291_p_din0;
input  [31:0] grp_fu_4291_p_dout0;
output   grp_fu_4291_p_ce;

reg ap_idle;
reg head_buf_ce0;
reg head_buf_1_ce0;
reg head_buf_2_ce0;
reg head_buf_3_ce0;
reg head_buf_4_ce0;
reg head_buf_5_ce0;
reg head_buf_6_ce0;
reg head_buf_7_ce0;
reg head_buf_8_ce0;
reg head_buf_9_ce0;
reg head_buf_10_ce0;
reg head_buf_11_ce0;
reg head_buf_12_ce0;
reg head_buf_13_ce0;
reg head_buf_14_ce0;
reg head_buf_15_ce0;
reg s0_4_out_ap_vld;
reg s1_4_out_ap_vld;
reg s2_4_out_ap_vld;
reg s3_4_out_ap_vld;
reg s4_4_out_ap_vld;
reg s5_4_out_ap_vld;
reg s6_4_out_ap_vld;
reg s7_4_out_ap_vld;
reg s8_4_out_ap_vld;
reg s9_4_out_ap_vld;
reg s10_4_out_ap_vld;
reg s11_4_out_ap_vld;
reg s12_4_out_ap_vld;
reg s13_4_out_ap_vld;
reg s14_4_out_ap_vld;
reg s15_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] tmp_reg_1363;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] p_ZL19reg_head_1_weight_q_0_address0;
reg    p_ZL19reg_head_1_weight_q_0_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_0_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_1_address0;
reg    p_ZL19reg_head_1_weight_q_1_ce0;
wire   [6:0] p_ZL19reg_head_1_weight_q_1_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_2_address0;
reg    p_ZL19reg_head_1_weight_q_2_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_2_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_3_address0;
reg    p_ZL19reg_head_1_weight_q_3_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_3_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_4_address0;
reg    p_ZL19reg_head_1_weight_q_4_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_4_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_5_address0;
reg    p_ZL19reg_head_1_weight_q_5_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_5_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_6_address0;
reg    p_ZL19reg_head_1_weight_q_6_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_6_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_7_address0;
reg    p_ZL19reg_head_1_weight_q_7_ce0;
wire   [6:0] p_ZL19reg_head_1_weight_q_7_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_8_address0;
reg    p_ZL19reg_head_1_weight_q_8_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_8_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_9_address0;
reg    p_ZL19reg_head_1_weight_q_9_ce0;
wire   [6:0] p_ZL19reg_head_1_weight_q_9_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_10_address0;
reg    p_ZL19reg_head_1_weight_q_10_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_10_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_11_address0;
reg    p_ZL19reg_head_1_weight_q_11_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_11_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_12_address0;
reg    p_ZL19reg_head_1_weight_q_12_ce0;
wire   [6:0] p_ZL19reg_head_1_weight_q_12_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_13_address0;
reg    p_ZL19reg_head_1_weight_q_13_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_13_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_14_address0;
reg    p_ZL19reg_head_1_weight_q_14_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_14_q0;
wire   [6:0] p_ZL19reg_head_1_weight_q_15_address0;
reg    p_ZL19reg_head_1_weight_q_15_ce0;
wire   [7:0] p_ZL19reg_head_1_weight_q_15_q0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_fu_884_p3;
reg   [0:0] tmp_reg_1363_pp0_iter1_reg;
reg   [0:0] tmp_reg_1363_pp0_iter2_reg;
reg   [0:0] tmp_reg_1363_pp0_iter3_reg;
wire   [3:0] lshr_ln5_fu_892_p4;
reg   [3:0] lshr_ln5_reg_1367;
reg   [7:0] p_ZL19reg_head_1_weight_q_0_load_reg_1452;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
reg   [6:0] p_ZL19reg_head_1_weight_q_1_load_reg_1457;
reg   [7:0] p_ZL19reg_head_1_weight_q_2_load_reg_1462;
reg   [7:0] p_ZL19reg_head_1_weight_q_3_load_reg_1467;
reg   [7:0] p_ZL19reg_head_1_weight_q_4_load_reg_1472;
reg   [7:0] p_ZL19reg_head_1_weight_q_5_load_reg_1477;
reg   [7:0] p_ZL19reg_head_1_weight_q_6_load_reg_1482;
reg   [6:0] p_ZL19reg_head_1_weight_q_7_load_reg_1487;
reg   [7:0] p_ZL19reg_head_1_weight_q_8_load_reg_1492;
reg   [6:0] p_ZL19reg_head_1_weight_q_9_load_reg_1497;
reg   [7:0] p_ZL19reg_head_1_weight_q_10_load_reg_1502;
reg   [7:0] p_ZL19reg_head_1_weight_q_11_load_reg_1507;
reg   [6:0] p_ZL19reg_head_1_weight_q_12_load_reg_1512;
reg   [7:0] p_ZL19reg_head_1_weight_q_13_load_reg_1517;
reg   [7:0] p_ZL19reg_head_1_weight_q_14_load_reg_1522;
reg   [7:0] p_ZL19reg_head_1_weight_q_15_load_reg_1527;
wire  signed [31:0] sext_ln193_fu_941_p1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
wire  signed [31:0] sext_ln194_fu_945_p1;
wire  signed [31:0] sext_ln195_fu_949_p1;
wire  signed [31:0] sext_ln196_fu_953_p1;
wire  signed [31:0] sext_ln197_fu_957_p1;
wire    ap_block_pp0_stage3_11001;
wire  signed [31:0] sext_ln198_fu_961_p1;
wire  signed [31:0] sext_ln199_fu_965_p1;
wire  signed [31:0] sext_ln200_fu_969_p1;
wire   [63:0] zext_ln193_fu_973_p1;
reg   [63:0] zext_ln193_reg_1572;
wire  signed [31:0] sext_ln201_fu_988_p1;
wire  signed [31:0] sext_ln202_fu_992_p1;
wire  signed [31:0] sext_ln203_fu_996_p1;
wire  signed [31:0] sext_ln204_fu_1000_p1;
reg   [31:0] conv_reg_1660;
reg   [31:0] head_buf_load_reg_1665;
reg   [31:0] conv1_reg_1670;
reg   [31:0] head_buf_1_load_reg_1675;
reg   [31:0] conv2_reg_1680;
reg   [31:0] head_buf_2_load_reg_1685;
reg   [31:0] conv3_reg_1690;
reg   [31:0] head_buf_3_load_reg_1695;
reg   [31:0] head_buf_4_load_reg_1700;
reg   [31:0] head_buf_5_load_reg_1705;
reg   [31:0] head_buf_6_load_reg_1710;
reg   [31:0] head_buf_7_load_reg_1715;
reg   [31:0] head_buf_8_load_reg_1720;
reg   [31:0] head_buf_9_load_reg_1725;
reg   [31:0] head_buf_10_load_reg_1730;
reg   [31:0] head_buf_11_load_reg_1735;
wire  signed [31:0] sext_ln205_fu_1004_p1;
wire  signed [31:0] sext_ln206_fu_1008_p1;
wire  signed [31:0] sext_ln207_fu_1012_p1;
wire  signed [31:0] sext_ln208_fu_1016_p1;
reg   [31:0] conv4_reg_1760;
reg   [31:0] conv5_reg_1765;
reg   [31:0] conv6_reg_1770;
reg   [31:0] conv7_reg_1775;
reg   [31:0] conv8_reg_1780;
reg   [31:0] conv9_reg_1785;
reg   [31:0] conv10_reg_1790;
reg   [31:0] conv11_reg_1795;
reg   [31:0] conv12_reg_1800;
reg   [31:0] conv13_reg_1810;
reg   [31:0] conv14_reg_1820;
reg   [31:0] conv15_reg_1830;
reg   [31:0] mul_reg_1840;
reg   [31:0] mul1_reg_1845;
reg   [31:0] mul2_reg_1850;
reg   [31:0] mul3_reg_1855;
reg   [31:0] mul4_reg_1900;
reg   [31:0] mul5_reg_1905;
reg   [31:0] mul6_reg_1910;
reg   [31:0] mul7_reg_1915;
reg   [31:0] mul8_reg_1940;
reg   [31:0] mul9_reg_1945;
reg   [31:0] mul10_reg_1950;
reg   [31:0] mul11_reg_1955;
reg   [31:0] mul12_reg_1980;
reg   [31:0] mul13_reg_1985;
reg   [31:0] mul14_reg_1990;
reg   [31:0] mul15_reg_1995;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln193_1_fu_910_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] s15_fu_146;
reg   [31:0] ap_sig_allocacmp_s15_load_1;
wire    ap_block_pp0_stage1;
wire    ap_loop_init;
reg   [31:0] s14_fu_150;
reg   [31:0] ap_sig_allocacmp_s14_load_1;
reg   [31:0] s13_fu_154;
reg   [31:0] ap_sig_allocacmp_s13_load_1;
reg   [31:0] s12_fu_158;
reg   [31:0] ap_sig_allocacmp_s12_load_1;
reg   [31:0] s11_fu_162;
reg   [31:0] ap_sig_allocacmp_s11_load_1;
reg   [31:0] s10_fu_166;
reg   [31:0] ap_sig_allocacmp_s10_load_1;
reg   [31:0] s9_fu_170;
reg   [31:0] ap_sig_allocacmp_s9_load_1;
reg   [31:0] s8_fu_174;
reg   [31:0] ap_sig_allocacmp_s8_load_1;
reg   [31:0] s7_fu_178;
reg   [31:0] ap_sig_allocacmp_s7_load_1;
wire    ap_block_pp0_stage3;
reg   [31:0] s6_fu_182;
reg   [31:0] ap_sig_allocacmp_s6_load_1;
reg   [31:0] s5_fu_186;
reg   [31:0] ap_sig_allocacmp_s5_load_1;
reg   [31:0] s4_fu_190;
reg   [31:0] ap_sig_allocacmp_s4_load_1;
reg   [31:0] s3_fu_194;
reg   [31:0] ap_sig_allocacmp_s3_load_1;
wire    ap_block_pp0_stage2;
reg   [31:0] s2_fu_198;
reg   [31:0] ap_sig_allocacmp_s2_load_1;
reg   [31:0] s1_fu_202;
reg   [31:0] ap_sig_allocacmp_s1_load_1;
reg   [31:0] s0_fu_206;
reg   [31:0] ap_sig_allocacmp_s0_load_1;
reg   [8:0] j_fu_210;
wire   [8:0] add_ln191_fu_930_p2;
reg   [8:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage1_01001;
reg   [31:0] grp_fu_748_p0;
reg   [31:0] grp_fu_748_p1;
reg   [31:0] grp_fu_752_p0;
reg   [31:0] grp_fu_752_p1;
reg   [31:0] grp_fu_756_p0;
reg   [31:0] grp_fu_756_p1;
reg   [31:0] grp_fu_760_p0;
reg   [31:0] grp_fu_760_p1;
reg   [31:0] grp_fu_764_p0;
reg   [31:0] grp_fu_764_p1;
reg   [31:0] grp_fu_768_p0;
reg   [31:0] grp_fu_768_p1;
reg   [31:0] grp_fu_772_p0;
reg   [31:0] grp_fu_772_p1;
reg   [31:0] grp_fu_776_p0;
reg   [31:0] grp_fu_776_p1;
reg  signed [31:0] grp_fu_784_p0;
reg  signed [31:0] grp_fu_787_p0;
reg  signed [31:0] grp_fu_790_p0;
reg  signed [31:0] grp_fu_793_p0;
wire   [6:0] add_ln2_fu_902_p3;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage1;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_0_address0),
    .ce0(p_ZL19reg_head_1_weight_q_0_ce0),
    .q0(p_ZL19reg_head_1_weight_q_0_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_1_address0),
    .ce0(p_ZL19reg_head_1_weight_q_1_ce0),
    .q0(p_ZL19reg_head_1_weight_q_1_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_2_address0),
    .ce0(p_ZL19reg_head_1_weight_q_2_ce0),
    .q0(p_ZL19reg_head_1_weight_q_2_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_3_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_3_address0),
    .ce0(p_ZL19reg_head_1_weight_q_3_ce0),
    .q0(p_ZL19reg_head_1_weight_q_3_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_4_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_4_address0),
    .ce0(p_ZL19reg_head_1_weight_q_4_ce0),
    .q0(p_ZL19reg_head_1_weight_q_4_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_5_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_5_address0),
    .ce0(p_ZL19reg_head_1_weight_q_5_ce0),
    .q0(p_ZL19reg_head_1_weight_q_5_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_6_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_6_address0),
    .ce0(p_ZL19reg_head_1_weight_q_6_ce0),
    .q0(p_ZL19reg_head_1_weight_q_6_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_7_ROM_1P_LUTRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_7_address0),
    .ce0(p_ZL19reg_head_1_weight_q_7_ce0),
    .q0(p_ZL19reg_head_1_weight_q_7_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_8_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_8_address0),
    .ce0(p_ZL19reg_head_1_weight_q_8_ce0),
    .q0(p_ZL19reg_head_1_weight_q_8_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_9_ROM_1P_LUTRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_9_address0),
    .ce0(p_ZL19reg_head_1_weight_q_9_ce0),
    .q0(p_ZL19reg_head_1_weight_q_9_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_10_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_10_address0),
    .ce0(p_ZL19reg_head_1_weight_q_10_ce0),
    .q0(p_ZL19reg_head_1_weight_q_10_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_11_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_11_address0),
    .ce0(p_ZL19reg_head_1_weight_q_11_ce0),
    .q0(p_ZL19reg_head_1_weight_q_11_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_12_ROM_1P_LUTRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_12_address0),
    .ce0(p_ZL19reg_head_1_weight_q_12_ce0),
    .q0(p_ZL19reg_head_1_weight_q_12_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_13_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_13_address0),
    .ce0(p_ZL19reg_head_1_weight_q_13_ce0),
    .q0(p_ZL19reg_head_1_weight_q_13_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_14_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_14_address0),
    .ce0(p_ZL19reg_head_1_weight_q_14_ce0),
    .q0(p_ZL19reg_head_1_weight_q_14_q0)
);

pb_predict_pb_predict_Pipeline_REG_H1_MAC_p_ZL19reg_head_1_weight_q_15_ROM_1P_LUTRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
p_ZL19reg_head_1_weight_q_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL19reg_head_1_weight_q_15_address0),
    .ce0(p_ZL19reg_head_1_weight_q_15_ce0),
    .q0(p_ZL19reg_head_1_weight_q_15_q0)
);

pb_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage1) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage1) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter3_stage1) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_884_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_210 <= add_ln191_fu_930_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_210 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_fu_206 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        s0_fu_206 <= grp_fu_2052_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s10_fu_166 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            s10_fu_166 <= grp_fu_4262_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s11_fu_162 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            s11_fu_162 <= grp_fu_4266_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s12_fu_158 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s12_fu_158 <= grp_fu_2052_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s13_fu_154 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s13_fu_154 <= grp_fu_4258_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s14_fu_150 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s14_fu_150 <= grp_fu_4262_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s15_fu_146 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s15_fu_146 <= grp_fu_4266_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_fu_202 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        s1_fu_202 <= grp_fu_4258_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s2_fu_198 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        s2_fu_198 <= grp_fu_4262_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s3_fu_194 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        s3_fu_194 <= grp_fu_4266_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s4_fu_190 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        s4_fu_190 <= grp_fu_2052_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s5_fu_186 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        s5_fu_186 <= grp_fu_4258_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s6_fu_182 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        s6_fu_182 <= grp_fu_4262_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s7_fu_178 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        s7_fu_178 <= grp_fu_4266_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s8_fu_174 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            s8_fu_174 <= grp_fu_2052_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s9_fu_170 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            s9_fu_170 <= grp_fu_4258_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        conv10_reg_1790 <= grp_fu_4288_p_dout0;
        conv11_reg_1795 <= grp_fu_4291_p_dout0;
        conv8_reg_1780 <= grp_fu_4282_p_dout0;
        conv9_reg_1785 <= grp_fu_4285_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv12_reg_1800 <= grp_fu_4282_p_dout0;
        conv13_reg_1810 <= grp_fu_4285_p_dout0;
        conv14_reg_1820 <= grp_fu_4288_p_dout0;
        conv15_reg_1830 <= grp_fu_4291_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        conv1_reg_1670 <= grp_fu_4285_p_dout0;
        conv2_reg_1680 <= grp_fu_4288_p_dout0;
        conv3_reg_1690 <= grp_fu_4291_p_dout0;
        conv_reg_1660 <= grp_fu_4282_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv4_reg_1760 <= grp_fu_4282_p_dout0;
        conv5_reg_1765 <= grp_fu_4285_p_dout0;
        conv6_reg_1770 <= grp_fu_4288_p_dout0;
        conv7_reg_1775 <= grp_fu_4291_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        head_buf_10_load_reg_1730 <= head_buf_10_q0;
        head_buf_11_load_reg_1735 <= head_buf_11_q0;
        head_buf_1_load_reg_1675 <= head_buf_1_q0;
        head_buf_2_load_reg_1685 <= head_buf_2_q0;
        head_buf_3_load_reg_1695 <= head_buf_3_q0;
        head_buf_4_load_reg_1700 <= head_buf_4_q0;
        head_buf_5_load_reg_1705 <= head_buf_5_q0;
        head_buf_6_load_reg_1710 <= head_buf_6_q0;
        head_buf_7_load_reg_1715 <= head_buf_7_q0;
        head_buf_8_load_reg_1720 <= head_buf_8_q0;
        head_buf_9_load_reg_1725 <= head_buf_9_q0;
        head_buf_load_reg_1665 <= head_buf_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_884_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln5_reg_1367 <= {{ap_sig_allocacmp_j_1[7:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul10_reg_1950 <= grp_fu_4274_p_dout0;
        mul11_reg_1955 <= grp_fu_4278_p_dout0;
        mul8_reg_1940 <= grp_fu_2057_p_dout0;
        mul9_reg_1945 <= grp_fu_4270_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul12_reg_1980 <= grp_fu_2057_p_dout0;
        mul13_reg_1985 <= grp_fu_4270_p_dout0;
        mul14_reg_1990 <= grp_fu_4274_p_dout0;
        mul15_reg_1995 <= grp_fu_4278_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul1_reg_1845 <= grp_fu_4270_p_dout0;
        mul2_reg_1850 <= grp_fu_4274_p_dout0;
        mul3_reg_1855 <= grp_fu_4278_p_dout0;
        mul_reg_1840 <= grp_fu_2057_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul4_reg_1900 <= grp_fu_2057_p_dout0;
        mul5_reg_1905 <= grp_fu_4270_p_dout0;
        mul6_reg_1910 <= grp_fu_4274_p_dout0;
        mul7_reg_1915 <= grp_fu_4278_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1363 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL19reg_head_1_weight_q_0_load_reg_1452 <= p_ZL19reg_head_1_weight_q_0_q0;
        p_ZL19reg_head_1_weight_q_10_load_reg_1502 <= p_ZL19reg_head_1_weight_q_10_q0;
        p_ZL19reg_head_1_weight_q_11_load_reg_1507 <= p_ZL19reg_head_1_weight_q_11_q0;
        p_ZL19reg_head_1_weight_q_12_load_reg_1512 <= p_ZL19reg_head_1_weight_q_12_q0;
        p_ZL19reg_head_1_weight_q_13_load_reg_1517 <= p_ZL19reg_head_1_weight_q_13_q0;
        p_ZL19reg_head_1_weight_q_14_load_reg_1522 <= p_ZL19reg_head_1_weight_q_14_q0;
        p_ZL19reg_head_1_weight_q_15_load_reg_1527 <= p_ZL19reg_head_1_weight_q_15_q0;
        p_ZL19reg_head_1_weight_q_1_load_reg_1457 <= p_ZL19reg_head_1_weight_q_1_q0;
        p_ZL19reg_head_1_weight_q_2_load_reg_1462 <= p_ZL19reg_head_1_weight_q_2_q0;
        p_ZL19reg_head_1_weight_q_3_load_reg_1467 <= p_ZL19reg_head_1_weight_q_3_q0;
        p_ZL19reg_head_1_weight_q_4_load_reg_1472 <= p_ZL19reg_head_1_weight_q_4_q0;
        p_ZL19reg_head_1_weight_q_5_load_reg_1477 <= p_ZL19reg_head_1_weight_q_5_q0;
        p_ZL19reg_head_1_weight_q_6_load_reg_1482 <= p_ZL19reg_head_1_weight_q_6_q0;
        p_ZL19reg_head_1_weight_q_7_load_reg_1487 <= p_ZL19reg_head_1_weight_q_7_q0;
        p_ZL19reg_head_1_weight_q_8_load_reg_1492 <= p_ZL19reg_head_1_weight_q_8_q0;
        p_ZL19reg_head_1_weight_q_9_load_reg_1497 <= p_ZL19reg_head_1_weight_q_9_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_1363 <= ap_sig_allocacmp_j_1[32'd8];
        tmp_reg_1363_pp0_iter1_reg <= tmp_reg_1363;
        tmp_reg_1363_pp0_iter2_reg <= tmp_reg_1363_pp0_iter1_reg;
        tmp_reg_1363_pp0_iter3_reg <= tmp_reg_1363_pp0_iter2_reg;
        zext_ln193_reg_1572[3 : 0] <= zext_ln193_fu_973_p1[3 : 0];
    end
end

always @ (*) begin
    if (((tmp_reg_1363 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter3_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_s0_load_1 = grp_fu_2052_p_dout0;
    end else begin
        ap_sig_allocacmp_s0_load_1 = s0_fu_206;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s10_load_1 = grp_fu_4262_p_dout0;
    end else begin
        ap_sig_allocacmp_s10_load_1 = s10_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s11_load_1 = grp_fu_4266_p_dout0;
    end else begin
        ap_sig_allocacmp_s11_load_1 = s11_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_s12_load_1 = grp_fu_2052_p_dout0;
    end else begin
        ap_sig_allocacmp_s12_load_1 = s12_fu_158;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_s13_load_1 = grp_fu_4258_p_dout0;
    end else begin
        ap_sig_allocacmp_s13_load_1 = s13_fu_154;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_s14_load_1 = grp_fu_4262_p_dout0;
    end else begin
        ap_sig_allocacmp_s14_load_1 = s14_fu_150;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_s15_load_1 = grp_fu_4266_p_dout0;
    end else begin
        ap_sig_allocacmp_s15_load_1 = s15_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_s1_load_1 = grp_fu_4258_p_dout0;
    end else begin
        ap_sig_allocacmp_s1_load_1 = s1_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_s2_load_1 = grp_fu_4262_p_dout0;
    end else begin
        ap_sig_allocacmp_s2_load_1 = s2_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_s3_load_1 = grp_fu_4266_p_dout0;
    end else begin
        ap_sig_allocacmp_s3_load_1 = s3_fu_194;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_s4_load_1 = grp_fu_2052_p_dout0;
    end else begin
        ap_sig_allocacmp_s4_load_1 = s4_fu_190;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_s5_load_1 = grp_fu_4258_p_dout0;
    end else begin
        ap_sig_allocacmp_s5_load_1 = s5_fu_186;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_s6_load_1 = grp_fu_4262_p_dout0;
    end else begin
        ap_sig_allocacmp_s6_load_1 = s6_fu_182;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_s7_load_1 = grp_fu_4266_p_dout0;
    end else begin
        ap_sig_allocacmp_s7_load_1 = s7_fu_178;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s8_load_1 = grp_fu_2052_p_dout0;
    end else begin
        ap_sig_allocacmp_s8_load_1 = s8_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s9_load_1 = grp_fu_4258_p_dout0;
    end else begin
        ap_sig_allocacmp_s9_load_1 = s9_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_748_p0 = ap_sig_allocacmp_s12_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_748_p0 = ap_sig_allocacmp_s8_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_748_p0 = ap_sig_allocacmp_s4_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_748_p0 = ap_sig_allocacmp_s0_load_1;
    end else begin
        grp_fu_748_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_748_p1 = mul12_reg_1980;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_748_p1 = mul8_reg_1940;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_748_p1 = mul4_reg_1900;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_748_p1 = mul_reg_1840;
    end else begin
        grp_fu_748_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_752_p0 = ap_sig_allocacmp_s13_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_752_p0 = ap_sig_allocacmp_s9_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_752_p0 = ap_sig_allocacmp_s5_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_752_p0 = ap_sig_allocacmp_s1_load_1;
    end else begin
        grp_fu_752_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_752_p1 = mul13_reg_1985;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_752_p1 = mul9_reg_1945;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_752_p1 = mul5_reg_1905;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_752_p1 = mul1_reg_1845;
    end else begin
        grp_fu_752_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_756_p0 = ap_sig_allocacmp_s14_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_756_p0 = ap_sig_allocacmp_s10_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_756_p0 = ap_sig_allocacmp_s6_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_756_p0 = ap_sig_allocacmp_s2_load_1;
    end else begin
        grp_fu_756_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_756_p1 = mul14_reg_1990;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_756_p1 = mul10_reg_1950;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_756_p1 = mul6_reg_1910;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_756_p1 = mul2_reg_1850;
    end else begin
        grp_fu_756_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_760_p0 = ap_sig_allocacmp_s15_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_760_p0 = ap_sig_allocacmp_s11_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_760_p0 = ap_sig_allocacmp_s7_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_760_p0 = ap_sig_allocacmp_s3_load_1;
    end else begin
        grp_fu_760_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_760_p1 = mul15_reg_1995;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_760_p1 = mul11_reg_1955;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_760_p1 = mul7_reg_1915;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_760_p1 = mul3_reg_1855;
    end else begin
        grp_fu_760_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_764_p0 = conv12_reg_1800;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_764_p0 = conv8_reg_1780;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_764_p0 = conv4_reg_1760;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_764_p0 = conv_reg_1660;
    end else begin
        grp_fu_764_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_764_p1 = head_buf_12_q0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_764_p1 = head_buf_8_load_reg_1720;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_764_p1 = head_buf_4_load_reg_1700;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_764_p1 = head_buf_load_reg_1665;
    end else begin
        grp_fu_764_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_768_p0 = conv13_reg_1810;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_768_p0 = conv9_reg_1785;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_768_p0 = conv5_reg_1765;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_768_p0 = conv1_reg_1670;
    end else begin
        grp_fu_768_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_768_p1 = head_buf_13_q0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_768_p1 = head_buf_9_load_reg_1725;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_768_p1 = head_buf_5_load_reg_1705;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_768_p1 = head_buf_1_load_reg_1675;
    end else begin
        grp_fu_768_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_772_p0 = conv14_reg_1820;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_772_p0 = conv10_reg_1790;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_772_p0 = conv6_reg_1770;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_772_p0 = conv2_reg_1680;
    end else begin
        grp_fu_772_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_772_p1 = head_buf_14_q0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_772_p1 = head_buf_10_load_reg_1730;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_772_p1 = head_buf_6_load_reg_1710;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_772_p1 = head_buf_2_load_reg_1685;
    end else begin
        grp_fu_772_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_776_p0 = conv15_reg_1830;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_776_p0 = conv11_reg_1795;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_776_p0 = conv7_reg_1775;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_776_p0 = conv3_reg_1690;
    end else begin
        grp_fu_776_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_776_p1 = head_buf_15_q0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_776_p1 = head_buf_11_load_reg_1735;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_776_p1 = head_buf_7_load_reg_1715;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_776_p1 = head_buf_3_load_reg_1695;
    end else begin
        grp_fu_776_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_784_p0 = sext_ln205_fu_1004_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_784_p0 = sext_ln201_fu_988_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_784_p0 = sext_ln197_fu_957_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_784_p0 = sext_ln193_fu_941_p1;
    end else begin
        grp_fu_784_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_787_p0 = sext_ln206_fu_1008_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_787_p0 = sext_ln202_fu_992_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_787_p0 = sext_ln198_fu_961_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_787_p0 = sext_ln194_fu_945_p1;
    end else begin
        grp_fu_787_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_790_p0 = sext_ln207_fu_1012_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_790_p0 = sext_ln203_fu_996_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_790_p0 = sext_ln199_fu_965_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_790_p0 = sext_ln195_fu_949_p1;
    end else begin
        grp_fu_790_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_793_p0 = sext_ln208_fu_1016_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_793_p0 = sext_ln204_fu_1000_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_793_p0 = sext_ln200_fu_969_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_793_p0 = sext_ln196_fu_953_p1;
    end else begin
        grp_fu_793_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_10_ce0 = 1'b1;
    end else begin
        head_buf_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_11_ce0 = 1'b1;
    end else begin
        head_buf_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_12_ce0 = 1'b1;
    end else begin
        head_buf_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_13_ce0 = 1'b1;
    end else begin
        head_buf_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_14_ce0 = 1'b1;
    end else begin
        head_buf_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_15_ce0 = 1'b1;
    end else begin
        head_buf_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_1_ce0 = 1'b1;
    end else begin
        head_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_2_ce0 = 1'b1;
    end else begin
        head_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_3_ce0 = 1'b1;
    end else begin
        head_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_4_ce0 = 1'b1;
    end else begin
        head_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_5_ce0 = 1'b1;
    end else begin
        head_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_6_ce0 = 1'b1;
    end else begin
        head_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_7_ce0 = 1'b1;
    end else begin
        head_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_8_ce0 = 1'b1;
    end else begin
        head_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_9_ce0 = 1'b1;
    end else begin
        head_buf_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        head_buf_ce0 = 1'b1;
    end else begin
        head_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_0_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_10_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_11_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_12_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_13_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_14_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_15_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_1_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_2_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_3_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_4_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_5_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_6_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_7_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_8_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19reg_head_1_weight_q_9_ce0 = 1'b1;
    end else begin
        p_ZL19reg_head_1_weight_q_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s0_4_out_ap_vld = 1'b1;
    end else begin
        s0_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s10_4_out_ap_vld = 1'b1;
    end else begin
        s10_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s11_4_out_ap_vld = 1'b1;
    end else begin
        s11_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s12_4_out_ap_vld = 1'b1;
    end else begin
        s12_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s13_4_out_ap_vld = 1'b1;
    end else begin
        s13_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s14_4_out_ap_vld = 1'b1;
    end else begin
        s14_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s15_4_out_ap_vld = 1'b1;
    end else begin
        s15_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s1_4_out_ap_vld = 1'b1;
    end else begin
        s1_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s2_4_out_ap_vld = 1'b1;
    end else begin
        s2_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s3_4_out_ap_vld = 1'b1;
    end else begin
        s3_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s4_4_out_ap_vld = 1'b1;
    end else begin
        s4_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s5_4_out_ap_vld = 1'b1;
    end else begin
        s5_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s6_4_out_ap_vld = 1'b1;
    end else begin
        s6_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s7_4_out_ap_vld = 1'b1;
    end else begin
        s7_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s8_4_out_ap_vld = 1'b1;
    end else begin
        s8_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (tmp_reg_1363_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s9_4_out_ap_vld = 1'b1;
    end else begin
        s9_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter3_stage1) & (ap_idle_pp0_0to2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln191_fu_930_p2 = (ap_sig_allocacmp_j_1 + 9'd16);

assign add_ln2_fu_902_p3 = {{i_5}, {lshr_ln5_fu_892_p4}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign grp_fu_2052_p_ce = 1'b1;

assign grp_fu_2052_p_din0 = grp_fu_748_p0;

assign grp_fu_2052_p_din1 = grp_fu_748_p1;

assign grp_fu_2052_p_opcode = 2'd0;

assign grp_fu_2057_p_ce = 1'b1;

assign grp_fu_2057_p_din0 = grp_fu_764_p0;

assign grp_fu_2057_p_din1 = grp_fu_764_p1;

assign grp_fu_4258_p_ce = 1'b1;

assign grp_fu_4258_p_din0 = grp_fu_752_p0;

assign grp_fu_4258_p_din1 = grp_fu_752_p1;

assign grp_fu_4258_p_opcode = 2'd0;

assign grp_fu_4262_p_ce = 1'b1;

assign grp_fu_4262_p_din0 = grp_fu_756_p0;

assign grp_fu_4262_p_din1 = grp_fu_756_p1;

assign grp_fu_4262_p_opcode = 2'd0;

assign grp_fu_4266_p_ce = 1'b1;

assign grp_fu_4266_p_din0 = grp_fu_760_p0;

assign grp_fu_4266_p_din1 = grp_fu_760_p1;

assign grp_fu_4266_p_opcode = 2'd0;

assign grp_fu_4270_p_ce = 1'b1;

assign grp_fu_4270_p_din0 = grp_fu_768_p0;

assign grp_fu_4270_p_din1 = grp_fu_768_p1;

assign grp_fu_4274_p_ce = 1'b1;

assign grp_fu_4274_p_din0 = grp_fu_772_p0;

assign grp_fu_4274_p_din1 = grp_fu_772_p1;

assign grp_fu_4278_p_ce = 1'b1;

assign grp_fu_4278_p_din0 = grp_fu_776_p0;

assign grp_fu_4278_p_din1 = grp_fu_776_p1;

assign grp_fu_4282_p_ce = 1'b1;

assign grp_fu_4282_p_din0 = grp_fu_784_p0;

assign grp_fu_4285_p_ce = 1'b1;

assign grp_fu_4285_p_din0 = grp_fu_787_p0;

assign grp_fu_4288_p_ce = 1'b1;

assign grp_fu_4288_p_din0 = grp_fu_790_p0;

assign grp_fu_4291_p_ce = 1'b1;

assign grp_fu_4291_p_din0 = grp_fu_793_p0;

assign head_buf_10_address0 = zext_ln193_fu_973_p1;

assign head_buf_11_address0 = zext_ln193_fu_973_p1;

assign head_buf_12_address0 = zext_ln193_reg_1572;

assign head_buf_13_address0 = zext_ln193_reg_1572;

assign head_buf_14_address0 = zext_ln193_reg_1572;

assign head_buf_15_address0 = zext_ln193_reg_1572;

assign head_buf_1_address0 = zext_ln193_fu_973_p1;

assign head_buf_2_address0 = zext_ln193_fu_973_p1;

assign head_buf_3_address0 = zext_ln193_fu_973_p1;

assign head_buf_4_address0 = zext_ln193_fu_973_p1;

assign head_buf_5_address0 = zext_ln193_fu_973_p1;

assign head_buf_6_address0 = zext_ln193_fu_973_p1;

assign head_buf_7_address0 = zext_ln193_fu_973_p1;

assign head_buf_8_address0 = zext_ln193_fu_973_p1;

assign head_buf_9_address0 = zext_ln193_fu_973_p1;

assign head_buf_address0 = zext_ln193_fu_973_p1;

assign lshr_ln5_fu_892_p4 = {{ap_sig_allocacmp_j_1[7:4]}};

assign p_ZL19reg_head_1_weight_q_0_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_10_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_11_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_12_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_13_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_14_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_15_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_1_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_2_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_3_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_4_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_5_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_6_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_7_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_8_address0 = zext_ln193_1_fu_910_p1;

assign p_ZL19reg_head_1_weight_q_9_address0 = zext_ln193_1_fu_910_p1;

assign s0_4_out = s0_fu_206;

assign s10_4_out = s10_fu_166;

assign s11_4_out = s11_fu_162;

assign s12_4_out = s12_fu_158;

assign s13_4_out = s13_fu_154;

assign s14_4_out = s14_fu_150;

assign s15_4_out = s15_fu_146;

assign s1_4_out = s1_fu_202;

assign s2_4_out = s2_fu_198;

assign s3_4_out = s3_fu_194;

assign s4_4_out = s4_fu_190;

assign s5_4_out = s5_fu_186;

assign s6_4_out = s6_fu_182;

assign s7_4_out = s7_fu_178;

assign s8_4_out = s8_fu_174;

assign s9_4_out = s9_fu_170;

assign sext_ln193_fu_941_p1 = $signed(p_ZL19reg_head_1_weight_q_0_load_reg_1452);

assign sext_ln194_fu_945_p1 = $signed(p_ZL19reg_head_1_weight_q_1_load_reg_1457);

assign sext_ln195_fu_949_p1 = $signed(p_ZL19reg_head_1_weight_q_2_load_reg_1462);

assign sext_ln196_fu_953_p1 = $signed(p_ZL19reg_head_1_weight_q_3_load_reg_1467);

assign sext_ln197_fu_957_p1 = $signed(p_ZL19reg_head_1_weight_q_4_load_reg_1472);

assign sext_ln198_fu_961_p1 = $signed(p_ZL19reg_head_1_weight_q_5_load_reg_1477);

assign sext_ln199_fu_965_p1 = $signed(p_ZL19reg_head_1_weight_q_6_load_reg_1482);

assign sext_ln200_fu_969_p1 = $signed(p_ZL19reg_head_1_weight_q_7_load_reg_1487);

assign sext_ln201_fu_988_p1 = $signed(p_ZL19reg_head_1_weight_q_8_load_reg_1492);

assign sext_ln202_fu_992_p1 = $signed(p_ZL19reg_head_1_weight_q_9_load_reg_1497);

assign sext_ln203_fu_996_p1 = $signed(p_ZL19reg_head_1_weight_q_10_load_reg_1502);

assign sext_ln204_fu_1000_p1 = $signed(p_ZL19reg_head_1_weight_q_11_load_reg_1507);

assign sext_ln205_fu_1004_p1 = $signed(p_ZL19reg_head_1_weight_q_12_load_reg_1512);

assign sext_ln206_fu_1008_p1 = $signed(p_ZL19reg_head_1_weight_q_13_load_reg_1517);

assign sext_ln207_fu_1012_p1 = $signed(p_ZL19reg_head_1_weight_q_14_load_reg_1522);

assign sext_ln208_fu_1016_p1 = $signed(p_ZL19reg_head_1_weight_q_15_load_reg_1527);

assign tmp_fu_884_p3 = ap_sig_allocacmp_j_1[32'd8];

assign zext_ln193_1_fu_910_p1 = add_ln2_fu_902_p3;

assign zext_ln193_fu_973_p1 = lshr_ln5_reg_1367;

always @ (posedge ap_clk) begin
    zext_ln193_reg_1572[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //pb_predict_pb_predict_Pipeline_REG_H1_MAC
