// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pb_predict_pb_predict_Pipeline_READ_INPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_TVALID,
        input_stream_TDATA,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        input_raw_5_out,
        input_raw_5_out_ap_vld,
        input_raw_4_out,
        input_raw_4_out_ap_vld,
        input_raw_3_out,
        input_raw_3_out_ap_vld,
        input_raw_2_out,
        input_raw_2_out_ap_vld,
        input_raw_1_out,
        input_raw_1_out_ap_vld,
        input_raw_out,
        input_raw_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_stream_TVALID;
input  [31:0] input_stream_TDATA;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [31:0] input_raw_5_out;
output   input_raw_5_out_ap_vld;
output  [31:0] input_raw_4_out;
output   input_raw_4_out_ap_vld;
output  [31:0] input_raw_3_out;
output   input_raw_3_out_ap_vld;
output  [31:0] input_raw_2_out;
output   input_raw_2_out_ap_vld;
output  [31:0] input_raw_1_out;
output   input_raw_1_out_ap_vld;
output  [31:0] input_raw_out;
output   input_raw_out_ap_vld;

reg ap_idle;
reg input_stream_TREADY;
reg input_raw_5_out_ap_vld;
reg input_raw_4_out_ap_vld;
reg input_raw_3_out_ap_vld;
reg input_raw_2_out_ap_vld;
reg input_raw_1_out_ap_vld;
reg input_raw_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln92_fu_150_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_TDATA_blk_n;
reg   [2:0] i_fu_60;
wire   [2:0] add_ln92_fu_156_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_3;
wire   [2:0] i_3_load_fu_147_p1;
reg   [31:0] input_raw_fu_64;
wire   [31:0] input_raw_6_fu_166_p1;
reg   [31:0] input_raw_1_fu_68;
reg   [31:0] input_raw_2_fu_72;
reg   [31:0] input_raw_3_fu_76;
reg   [31:0] input_raw_4_fu_80;
reg   [31:0] input_raw_5_fu_84;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_167;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

pb_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_167)) begin
        if ((icmp_ln92_fu_150_p2 == 1'd0)) begin
            i_fu_60 <= add_ln92_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (i_3_load_fu_147_p1 == 3'd1) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_1_fu_68 <= input_raw_6_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (i_3_load_fu_147_p1 == 3'd2) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_2_fu_72 <= input_raw_6_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (i_3_load_fu_147_p1 == 3'd3) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_3_fu_76 <= input_raw_6_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (i_3_load_fu_147_p1 == 3'd4) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_4_fu_80 <= input_raw_6_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_3_load_fu_147_p1 == 3'd4) & ~(i_3_load_fu_147_p1 == 3'd3) & ~(i_3_load_fu_147_p1 == 3'd2) & ~(i_3_load_fu_147_p1 == 3'd1) & ~(i_3_load_fu_147_p1 == 3'd0) & ~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_5_fu_84 <= input_raw_6_fu_166_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (i_3_load_fu_147_p1 == 3'd0) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_fu_64 <= input_raw_6_fu_166_p1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_60;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_1_out_ap_vld = 1'b1;
    end else begin
        input_raw_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_2_out_ap_vld = 1'b1;
    end else begin
        input_raw_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_3_out_ap_vld = 1'b1;
    end else begin
        input_raw_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_4_out_ap_vld = 1'b1;
    end else begin
        input_raw_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_5_out_ap_vld = 1'b1;
    end else begin
        input_raw_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_raw_out_ap_vld = 1'b1;
    end else begin
        input_raw_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        input_stream_TDATA_blk_n = input_stream_TVALID;
    end else begin
        input_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (icmp_ln92_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_stream_TREADY = 1'b1;
    end else begin
        input_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln92_fu_156_p2 = (ap_sig_allocacmp_i_3 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_167 = (~((ap_start_int == 1'b0) | ((icmp_ln92_fu_150_p2 == 1'd0) & (input_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_3_load_fu_147_p1 = ap_sig_allocacmp_i_3;

assign icmp_ln92_fu_150_p2 = ((ap_sig_allocacmp_i_3 == 3'd6) ? 1'b1 : 1'b0);

assign input_raw_1_out = input_raw_1_fu_68;

assign input_raw_2_out = input_raw_2_fu_72;

assign input_raw_3_out = input_raw_3_fu_76;

assign input_raw_4_out = input_raw_4_fu_80;

assign input_raw_5_out = input_raw_5_fu_84;

assign input_raw_6_fu_166_p1 = input_stream_TDATA;

assign input_raw_out = input_raw_fu_64;

endmodule //pb_predict_pb_predict_Pipeline_READ_INPUT
